### PR TITLE
workaround for glcore crash with Mesa

### LINKED ISSUE #9277: glcore broken on master
## Description

glcore is currently broken on master as of https://github.com/libretro/RetroArch/commit/2b6613c137a2de8379c7ce1571a21bbbb56c9160

I know master is wip and stuff is expected to get broken )
I open this issue just to let you know about this problem, please close the issue if this is expected.

### Expected behavior

retroarch works with glcore

### Actual behavior

retroarch just exits with 1, no crash, no backtrace,
gl driver works, vulkan driver works
glcore does not

log
```
[INFO] RetroArch 1.7.7 (Git 2b6613c137)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 2400G with Radeon Vega Graphics
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES
[INFO] Built: Aug 11 2019
[INFO] Version: 1.7.7
[INFO] Git: 2b6613c137
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
[INFO] [GLCore]: Found GL context: x
[INFO] [GLCore]: Detecting screen resolution 3840x2160.
[INFO] [GLX]: Window manager is Openbox.
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [GLX]: Using Xinerama on screen #0.
[INFO] [GLX]: X = 0, Y = 0, W = 3840, H = 2160.
[INFO] [GLX]: Using true fullscreen.
```
exits with 1

### Steps to reproduce the bug

1. Move away ~./config/retroarch to start from scratch with defaults
2. Run retroarch.
3. Select glcore as video driver
4. Save config and exit retroarch
5. Try running retroarch again.

### Bisect Results
759591d5a60ee91291d9068569816f6d717f451f last good
a88b357817f95960701caf88c4a3aefb97f54786 first bad #9250 

~~Edit: I'll try to narrow this down later.
I didn't do a full/proper bisect, however https://github.com/libretro/RetroArch/commit/881ef63b630eec5bc4eaea2c387f32750389aa10 works fine here , I tried building a few commits between 82168c0 and current tip and none worked.~~
working log from 881ef63
```
[INFO] RetroArch 1.7.7 (Git 881ef63b63)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 2400G with Radeon Vega Graphics
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES
[INFO] Built: Aug 11 2019
[INFO] Version: 1.7.7
[INFO] Git: 881ef63b63
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
[INFO] [GLCore]: Found GL context: x
[INFO] [GLCore]: Detecting screen resolution 3840x2160.
[INFO] [GLX]: Window manager is Openbox.
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [GLX]: Using Xinerama on screen #0.
[INFO] [GLX]: X = 0, Y = 0, W = 3840, H = 2160.
[INFO] [GLX]: Using true fullscreen.
[INFO] [GLX]: Found swap function: glXSwapIntervalMESA.
[INFO] [GLX]: glXSwapInterval(0)
[INFO] [GLCore]: Vendor: X.Org, Renderer: AMD RAVEN (DRM 3.32.0, 5.2.8-k1, LLVM 9.0.0).
[INFO] [GLCore]: Version: 4.5 (Core Profile) Mesa 19.1.4.
[INFO] [GLCore]: Using resolution 3840x2160
[INFO] [udev]: Plugged pad: Microsoft X-Box One S pad (1118:746) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event18) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event18) supports 16 force feedback effects.
[INFO] [Autoconf]: 1 profiles found.
[INFO] [Autoconf]: no profiles found for Microsoft X-Box One S pad (1118/746).
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [GLCore]: Loading stock shader.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]:   Textures:
[INFO] [slang]:      Source (#0)
[INFO] [slang]:
[INFO] [slang]:   Uniforms (Vertex: yes, Fragment: no):
[INFO] [slang]:   Push Constants (Vertex: no, Fragment: no):
[INFO] [slang]:      MVP (Offset: 0)
[INFO] [slang]:
[INFO] [slang]:   Parameters:
[INFO] [GLCore]: Not using frame history.
[INFO] [GLCore]: Not using framebuffer feedback.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: x11
[INFO] Found shader "/usr/share/libretro/shaders/stock.slang"
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 29024.
[INFO] [Menu]: Found menu display driver: "glcore".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Menu]: Found menu display driver: "glcore".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x55c04f3c0820
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "alsa" driver.
[WARN] Input device ID 5 is unknown to this libretro implementation. Using RETRO_DEVICE_JOYPAD.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_image_history.lpl].
[INFO] Loading favorites file: [/home/kodi/.config/retroarch/content_favorites.lpl].
[INFO] [GLCore]: VSync => off
[INFO] [GLX]: glXSwapInterval(0)
[INFO] [GLCore]: VSync => on
[INFO] [GLX]: glXSwapInterval(0)
[INFO] [config] Saved new config to "/home/kodi/.config/retroarch/retroarch.cfg".
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] [PulseAudio]: Pausing.
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [XINERAMA]: Saved monitor #0.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
```

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [2b6613c137]

### Environment information

- OS: linux (own distro) , kernel 5.2.8 , glibc 2.30, Xorg, mesa 19.1.4
- Compiler: gcc 9.1, binutils 2.28
- GPU (actually APU) is AMD 2400G (Raven) , OpenGL 4.5, mesa 19.1.4

### PR DESCRIPTION
**Pull request by LazyBumHorse**
## (Updated) Description

#9250 caused glcore to break on Mesa drivers because of
 - an `exit` call in the error handler
 - a [2 year old bug](https://bugs.freedesktop.org/show_bug.cgi?id=99781)

This PR fixes the first part and works around the second by trying the requested version first, detecting Mesa and only searching for higher versions for non-Mesa drivers.

Mesa seems to always return the highest compatible version anyways, so it doesn't lose out.
Ideally the workaround will be removed in the future, which is why I didn't fiddle it into the loop but wrote it as a perfectly select-and-deletable block of code.

I also added all the verbose error logging @bparker06 requested and fixed an issue where `attribs` could be garbled.

## Related Issues

Fixes #9277

## Related Pull Requests

#9250

## Reviewers
@bparker06 @asavah

### CODE REVIEW

**Comment by LazyBumHorse** [comment]
Hm... actually it did not use `XSetErrorHandler` at all before, so removing the call should be better

**Comment by twinaphex** [comment]
OK, who could reproduce the issue that this PR is supposed to fix, and can we get him/her to test this one?

**Comment by LazyBumHorse** [comment]
@asavah said he can test

**Comment by retro-wertz** [comment]
im one having glcore loading issue and i confirm that this PR does not cause RA to close itself anymore. (linux x64, intel mesa)

**Comment by asavah** [comment]
I'm having segfaults with this PR applied on top of https://github.com/libretro/RetroArch/commit/ab293b99000122a3a68859255cf11974bc4f0b94

backtrace is not useful as it's not a debug build.

**Comment by hizzlekizzle** [comment]
I get the same result as asavah

**Comment by LazyBumHorse** [comment]
Can you try reverting #9250 on master, so we know this new error has nothing to do with this code?

**Comment by LazyBumHorse** [comment]
Description of the 2nd commit:
It uses `XGetErrorText` for a more detailed description why a context could not be created.
This only applies for the very last tried version (the requested version), so we don't get so much log spam for the higher versions.

[Reference](https://www.khronos.org/registry/OpenGL/extensions/ARB/GLX_ARB_create_context.txt):
> On failure glXCreateContextAttribsARB returns NULL and generates an X error with extended error information

File: gfx/drivers_context/x_ctx.c [hunk 1]
```diff
@@ -916,10 +904,20 @@ static bool gfx_ctx_x_set_video_mode(void *data,
...
-                     else if (versions[i][0] == g_major && versions[i][1] == g_minor)
+                     else 
                      {
-                        /* The requested version was tried and is not supported, go ahead and fail since everything else will be lower than that. */
-                        break;
+                        if (versions[i][0] == g_major && versions[i][1] == g_minor)
+                        {
+                           /* last version reached, time to fail */
+                           char buf[2048];
+                           XGetErrorText(last_dpy, last_error_code, buf, sizeof buf);
```
Comment (bparker06) [inline gfx/drivers_context/x_ctx.c]: Sorry I should have been more clear... my suggestion was to put `XGetErrorText()` in the error handler function itself, that way, *any* X11 error is printed.

**Comment by asavah** [comment]
> Can you try reverting #9250 on master, so we know this new error has a different cause?

Done, with #9250 reverted master runs fine with glcore.

With this PR updates and #9250 present the error message is exactly the same.
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
retroarch: xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```

**Comment by bparker06** [comment]
That particular error doesn't make any sense to me, nor does it appear even related to any of these PRs... `XInitThreads()` is already called basically as early as possible in the driver initialization, so I don't see how that can be an issue. Maybe there's some extra logic missing that we must do when an error is triggered? Not sure.

File: gfx/drivers_context/x_ctx.c (hunk 1 above)
Comment (LazyBumHorse) [reply gfx/drivers_context/x_ctx.c]: I don't really get this...
The old `x_gl_version_error_handler` was only used for this part of the code and only effective for `glx_create_context_attribs` (aka glXCreateContextAttribsARB).
In this version, the error handling still only applies to `glx_create_context_attribs`, so what errors are there to catch?

**Comment by LazyBumHorse** [comment]
Yeah, that's really odd, what does context creation have to do with threads?

Do you use the `video_threaded` setting?
Maybe trying the default config does something, I don't know.

**Comment by asavah** [comment]
```
grep thread retroarch.cfg
threaded_data_runloop_enable = "true"
video_record_threads = "2"
video_threaded = "false"
```

**Comment by LazyBumHorse** [comment]
@bparker06 
Hm... actually, what do these changes in task_content.c do?
https://github.com/libretro/RetroArch/pull/9250/files#diff-5b4b98202ea8ff3448e09fd786674bf3R584-R629

Maybe setting `threaded_data_runloop_enable` to `false` will do something because it's used in task_queue.c which is somewhat related.

**Comment by bparker06** [comment]
It checks the required graphics API/version for the core from its core info and prevents loading the content if there is a mismatch (e.g. d3d is being used when trying to load the GL-only mupen), but content loading is not technically a task, and doesn't use threads, so it should not be related.

**Comment by LazyBumHorse** [comment]
We need to find the minimal failing example.

I reverted #9250 and only added the loop around `glx_create_context_attribs` here, does this still fail?
https://github.com/LazyBumHorse/RetroArch/tree/debug_9250

It should output something like
> [DEBUG] replacing version -1111.-1111 with 4.6
> [DEBUG] failed
> [DEBUG] replacing version 4.6 with 4.5
> [DEBUG] success

**Comment by asavah** [comment]
https://github.com/LazyBumHorse/RetroArch/commit/6c85d9b17770b9a48c47982fdc6d4b12affe5e3b fails to build as is,
```
gfx/drivers_context/x_ctx.c:863:17: error: ‘version_rows’ undeclared (first use in this function); did you mean ‘gl_version_rows’?
  863 | for (i = 0; i < version_rows; i++)
      |                 ^~~~~~~~~~~~
      |                 gl_version_rows
gfx/drivers_context/x_ctx.c:863:17: note: each undeclared identifier is reported only once for each function it appears in
gfx/drivers_context/x_ctx.c:865:83: error: ‘versions’ undeclared (first use in this function); did you mean ‘gl_versions’?
  865 | RARCH_LOG("[DEBUG] replacing version %d.%d with %d.%d\n", attribs[1], attribs[3], versions[i][0], versions[i][1]);
      |                                                                                   ^~~~~~~~
      |                                                                                   gl_versions

```
however the fix was trivial even for me ).

output
```
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  76
  Current serial number in output stream:  75
```

**Comment by LazyBumHorse** [comment]
This is all it prints?
Does this mean it uses some kind of default error handler that `exit`s?

Alright, let's readd an error handler...
There you go, you can pull and test again.

**Comment by asavah** [comment]
```
gfx/drivers_context/x_ctx.c:870:31: error: ‘gl_versions’ undeclared (first use in this function); did you mean ‘versions’?
  870 | int version_rows = ARRAY_SIZE(gl_versions);
      |                               ^~~~~~~~~~~
```
again trivial fix ))

```
retroach -v --log-file /dev/stdout
[INFO] RetroArch 1.7.7 (Git d4de1eaf7d)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 2400G with Radeon Vega Graphics
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AVX2 AES
[INFO] Built: Aug 11 2019
[INFO] Version: 1.7.7
[INFO] Git: d4de1eaf7d
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
[INFO] [GLCore]: Found GL context: x
[INFO] [GLCore]: Detecting screen resolution 3840x2160.
[INFO] [GLX]: Window manager is Openbox.
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [GLX]: Using Xinerama on screen #0.
[INFO] [GLX]: X = 0, Y = 0, W = 3840, H = 2160.
[INFO] [GLX]: Using true fullscreen.
[INFO] [DEBUG] replacing version -1111.-1111 with 4.6
[WARN] [GLX]: message: GLXBadFBConfig, request code: 152, minor code: 34
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
retroarch: xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```

It looks like XinitThreads is being called later than expexted ?

**Comment by LazyBumHorse** [comment]
Hm... it doesn't even reach the "[DEBUG] failed/success"?

Okay, 3 hypotheses:
1. The `glx_create_context_attribs` itself fails (uh oh...)
1. The second `XSetErrorHandler` fails (?)
1. The buffer is not flushed, so we can't read the actual logs

**Comment by LazyBumHorse** [comment]
Okay, let's log the `XInitThreads` call, add more logs and `fflush(stdout)` just to be sure.
https://github.com/LazyBumHorse/RetroArch/commit/4e96680e1e535878f6f4abcce6237c298e830054

**Comment by asavah** [comment]
```
retroarch -v --log-file /dev/stdout
[INFO] RetroArch 1.7.7 (Git d4de1eaf7d)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 2400G with Radeon Vega Graphics
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AVX2 AES
[INFO] Built: Aug 11 2019
[INFO] Version: 1.7.7
[INFO] Git: d4de1eaf7d
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [DEBUG] XInitThreads()
[INFO] [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
[INFO] [GLCore]: Found GL context: x
[INFO] [GLCore]: Detecting screen resolution 3840x2160.
[INFO] [GLX]: Window manager is Openbox.
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [GLX]: Using Xinerama on screen #0.
[INFO] [GLX]: X = 0, Y = 0, W = 3840, H = 2160.
[INFO] [GLX]: Using true fullscreen.
[INFO] [DEBUG] replacing version -1111.-1111 with 4.6
[INFO] [DEBUG] glx_create_context_attribs()
[WARN] [DEBUG]: message: GLXBadFBConfig, request code: 152, minor code: 34
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
retroarch: xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```

**Comment by LazyBumHorse** [comment]
`XInitThreads` is called as expected, but no additional logs show, which means it _is_ `glx_create_context_attribs` itself that fails and dumps the core... wat

Alright, checking the [glXCreateContextAttribsARB documentation](https://www.khronos.org/registry/OpenGL/extensions/ARB/GLX_ARB_create_context.txt):
> If \<config\> is not a valid GLXFBConfig, GLXBadFBConfig is generated.
> If \<config\> does not support compatible OpenGL contexts providing the requested API major and minor version, forward-compatible flag, and debug context flag, GLXBadFBConfig is generated.

In this case this has to be the latter because it succeeds with smaller versions.
The question is why we don't seem to be able to actually catch this error and ignore it.

**Comment by LazyBumHorse** [comment]
Out of curiosity, what does it print with the gl video driver?

**Comment by asavah** [comment]
video_driver="gl"
```
retroarch -v --log-file /dev/stdout
[INFO] RetroArch 1.7.7 (Git d4de1eaf7d)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 2400G with Radeon Vega Graphics
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AVX2 AES
[INFO] Built: Aug 11 2019
[INFO] Version: 1.7.7
[INFO] Git: d4de1eaf7d
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [DEBUG] XInitThreads()
[INFO] [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 3840x2160.
[INFO] [GLX]: Window manager is Openbox.
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [GLX]: Using Xinerama on screen #0.
[INFO] [GLX]: X = 0, Y = 0, W = 3840, H = 2160.
[INFO] [GLX]: Using true fullscreen.
[INFO] [DEBUG] replacing version 1.-2222 with 4.6
[INFO] [DEBUG] glx_create_context_attribs()
[INFO] [DEBUG] XSetErrorHandler(old_handler)
[INFO] [DEBUG] success
[INFO] [GLX]: Found swap function: glXSwapIntervalMESA.
[INFO] [GLX]: glXSwapInterval(0)
[INFO] [GL]: Vendor: X.Org, Renderer: AMD RAVEN (DRM 3.32.0, 5.2.8-k1, LLVM 9.0.0).
[INFO] [GL]: Version: 4.5 (Compatibility Profile) Mesa 19.1.4.
[INFO] [GL]: Supported extensions:
[INFO]  GL_ARB_multisample
[INFO]  GL_EXT_abgr
[INFO]  GL_EXT_bgra
[INFO]  GL_EXT_blend_color
[INFO]  GL_EXT_blend_minmax
[INFO]  GL_EXT_blend_subtract
[INFO]  GL_EXT_copy_texture
[INFO]  GL_EXT_subtexture
[INFO]  GL_EXT_texture_object
[INFO]  GL_EXT_vertex_array
[INFO]  GL_EXT_compiled_vertex_array
[INFO]  GL_EXT_texture
[INFO]  GL_EXT_texture3D
[INFO]  GL_IBM_rasterpos_clip
[INFO]  GL_ARB_point_parameters
[INFO]  GL_EXT_draw_range_elements
[INFO]  GL_EXT_packed_pixels
[INFO]  GL_EXT_point_parameters
[INFO]  GL_EXT_rescale_normal
[INFO]  GL_EXT_separate_specular_color
[INFO]  GL_EXT_texture_edge_clamp
[INFO]  GL_SGIS_generate_mipmap
[INFO]  GL_SGIS_texture_border_clamp
[INFO]  GL_SGIS_texture_edge_clamp
[INFO]  GL_SGIS_texture_lod
[INFO]  GL_ARB_framebuffer_sRGB
[INFO]  GL_ARB_multitexture
[INFO]  GL_EXT_framebuffer_sRGB
[INFO]  GL_IBM_multimode_draw_arrays
[INFO]  GL_IBM_texture_mirrored_repeat
[INFO]  GL_ARB_texture_cube_map
[INFO]  GL_ARB_texture_env_add
[INFO]  GL_ARB_transpose_matrix
[INFO]  GL_EXT_blend_func_separate
[INFO]  GL_EXT_fog_coord
[INFO]  GL_EXT_multi_draw_arrays
[INFO]  GL_EXT_secondary_color
[INFO]  GL_EXT_texture_env_add
[INFO]  GL_EXT_texture_filter_anisotropic
[INFO]  GL_EXT_texture_lod_bias
[INFO]  GL_INGR_blend_func_separate
[INFO]  GL_NV_blend_square
[INFO]  GL_NV_light_max_exponent
[INFO]  GL_NV_texgen_reflection
[INFO]  GL_NV_texture_env_combine4
[INFO]  GL_S3_s3tc
[INFO]  GL_SUN_multi_draw_arrays
[INFO]  GL_ARB_texture_border_clamp
[INFO]  GL_ARB_texture_compression
[INFO]  GL_EXT_framebuffer_object
[INFO]  GL_EXT_texture_compression_s3tc
[INFO]  GL_EXT_texture_env_combine
[INFO]  GL_EXT_texture_env_dot3
[INFO]  GL_MESA_window_pos
[INFO]  GL_NV_packed_depth_stencil
[INFO]  GL_NV_texture_rectangle
[INFO]  GL_ARB_depth_texture
[INFO]  GL_ARB_occlusion_query
[INFO]  GL_ARB_shadow
[INFO]  GL_ARB_texture_env_combine
[INFO]  GL_ARB_texture_env_crossbar
[INFO]  GL_ARB_texture_env_dot3
[INFO]  GL_ARB_texture_mirrored_repeat
[INFO]  GL_ARB_window_pos
[INFO]  GL_ATI_fragment_shader
[INFO]  GL_EXT_stencil_two_side
[INFO]  GL_EXT_texture_cube_map
[INFO]  GL_NV_depth_clamp
[INFO]  GL_NV_fog_distance
[INFO]  GL_APPLE_packed_pixels
[INFO]  GL_ARB_draw_buffers
[INFO]  GL_ARB_fragment_program
[INFO]  GL_ARB_fragment_shader
[INFO]  GL_ARB_shader_objects
[INFO]  GL_ARB_vertex_program
[INFO]  GL_ARB_vertex_shader
[INFO]  GL_ATI_draw_buffers
[INFO]  GL_ATI_texture_env_combine3
[INFO]  GL_ATI_texture_float
[INFO]  GL_EXT_depth_bounds_test
[INFO]  GL_EXT_shadow_funcs
[INFO]  GL_EXT_stencil_wrap
[INFO]  GL_MESA_pack_invert
[INFO]  GL_NV_primitive_restart
[INFO]  GL_ARB_depth_clamp
[INFO]  GL_ARB_fragment_program_shadow
[INFO]  GL_ARB_half_float_pixel
[INFO]  GL_ARB_occlusion_query2
[INFO]  GL_ARB_point_sprite
[INFO]  GL_ARB_shading_language_100
[INFO]  GL_ARB_sync
[INFO]  GL_ARB_texture_non_power_of_two
[INFO]  GL_ARB_vertex_buffer_object
[INFO]  GL_ATI_blend_equation_separate
[INFO]  GL_EXT_blend_equation_separate
[INFO]  GL_OES_read_format
[INFO]  GL_ARB_color_buffer_float
[INFO]  GL_ARB_pixel_buffer_object
[INFO]  GL_ARB_texture_compression_rgtc
[INFO]  GL_ARB_texture_float
[INFO]  GL_ARB_texture_rectangle
[INFO]  GL_ATI_texture_compression_3dc
[INFO]  GL_EXT_packed_float
[INFO]  GL_EXT_pixel_buffer_object
[INFO]  GL_EXT_texture_compression_dxt1
[INFO]  GL_EXT_texture_compression_rgtc
[INFO]  GL_EXT_texture_mirror_clamp
[INFO]  GL_EXT_texture_rectangle
[INFO]  GL_EXT_texture_sRGB
[INFO]  GL_EXT_texture_shared_exponent
[INFO]  GL_ARB_framebuffer_object
[INFO]  GL_EXT_framebuffer_blit
[INFO]  GL_EXT_framebuffer_multisample
[INFO]  GL_EXT_packed_depth_stencil
[INFO]  GL_ARB_vertex_array_object
[INFO]  GL_ATI_separate_stencil
[INFO]  GL_ATI_texture_mirror_once
[INFO]  GL_EXT_draw_buffers2
[INFO]  GL_EXT_draw_instanced
[INFO]  GL_EXT_gpu_program_parameters
[INFO]  GL_EXT_gpu_shader4
[INFO]  GL_EXT_texture_array
[INFO]  GL_EXT_texture_compression_latc
[INFO]  GL_EXT_texture_integer
[INFO]  GL_EXT_texture_sRGB_decode
[INFO]  GL_EXT_timer_query
[INFO]  GL_OES_EGL_image
[INFO]  GL_AMD_performance_monitor
[INFO]  GL_EXT_texture_buffer_object
[INFO]  GL_AMD_texture_texture4
[INFO]  GL_ARB_copy_buffer
[INFO]  GL_ARB_depth_buffer_float
[INFO]  GL_ARB_draw_instanced
[INFO]  GL_ARB_half_float_vertex
[INFO]  GL_ARB_instanced_arrays
[INFO]  GL_ARB_map_buffer_range
[INFO]  GL_ARB_texture_buffer_object
[INFO]  GL_ARB_texture_rg
[INFO]  GL_ARB_texture_swizzle
[INFO]  GL_ARB_vertex_array_bgra
[INFO]  GL_EXT_texture_swizzle
[INFO]  GL_EXT_vertex_array_bgra
[INFO]  GL_NV_conditional_render
[INFO]  GL_AMD_conservative_depth
[INFO]  GL_AMD_depth_clamp_separate
[INFO]  GL_AMD_draw_buffers_blend
[INFO]  GL_AMD_seamless_cubemap_per_texture
[INFO]  GL_AMD_shader_stencil_export
[INFO]  GL_ARB_ES2_compatibility
[INFO]  GL_ARB_blend_func_extended
[INFO]  GL_ARB_compatibility
[INFO]  GL_ARB_debug_output
[INFO]  GL_ARB_draw_buffers_blend
[INFO]  GL_ARB_draw_elements_base_vertex
[INFO]  GL_ARB_explicit_attrib_location
[INFO]  GL_ARB_fragment_coord_conventions
[INFO]  GL_ARB_provoking_vertex
[INFO]  GL_ARB_sample_shading
[INFO]  GL_ARB_sampler_objects
[INFO]  GL_ARB_seamless_cube_map
[INFO]  GL_ARB_shader_stencil_export
[INFO]  GL_ARB_shader_texture_lod
[INFO]  GL_ARB_tessellation_shader
[INFO]  GL_ARB_texture_buffer_object_rgb32
[INFO]  GL_ARB_texture_cube_map_array
[INFO]  GL_ARB_texture_gather
[INFO]  GL_ARB_texture_multisample
[INFO]  GL_ARB_texture_query_lod
[INFO]  GL_ARB_texture_rgb10_a2ui
[INFO]  GL_ARB_uniform_buffer_object
[INFO]  GL_ARB_vertex_type_2_10_10_10_rev
[INFO]  GL_ATI_meminfo
[INFO]  GL_EXT_provoking_vertex
[INFO]  GL_EXT_texture_snorm
[INFO]  GL_MESA_texture_signed_rgba
[INFO]  GL_NV_texture_barrier
[INFO]  GL_ARB_draw_indirect
[INFO]  GL_ARB_get_program_binary
[INFO]  GL_ARB_gpu_shader5
[INFO]  GL_ARB_gpu_shader_fp64
[INFO]  GL_ARB_robustness
[INFO]  GL_ARB_separate_shader_objects
[INFO]  GL_ARB_shader_bit_encoding
[INFO]  GL_ARB_shader_precision
[INFO]  GL_ARB_shader_subroutine
[INFO]  GL_ARB_texture_compression_bptc
[INFO]  GL_ARB_timer_query
[INFO]  GL_ARB_transform_feedback2
[INFO]  GL_ARB_transform_feedback3
[INFO]  GL_ARB_vertex_attrib_64bit
[INFO]  GL_ARB_viewport_array
[INFO]  GL_EXT_vertex_attrib_64bit
[INFO]  GL_AMD_multi_draw_indirect
[INFO]  GL_ANGLE_texture_compression_dxt3
[INFO]  GL_ANGLE_texture_compression_dxt5
[INFO]  GL_ARB_base_instance
[INFO]  GL_ARB_compressed_texture_pixel_storage
[INFO]  GL_ARB_conservative_depth
[INFO]  GL_ARB_internalformat_query
[INFO]  GL_ARB_map_buffer_alignment
[INFO]  GL_ARB_shader_atomic_counters
[INFO]  GL_ARB_shader_image_load_store
[INFO]  GL_ARB_shading_language_420pack
[INFO]  GL_ARB_shading_language_packing
[INFO]  GL_ARB_texture_storage
[INFO]  GL_ARB_transform_feedback_instanced
[INFO]  GL_EXT_framebuffer_multisample_blit_scaled
[INFO]  GL_EXT_transform_feedback
[INFO]  GL_AMD_query_buffer_object
[INFO]  GL_AMD_shader_trinary_minmax
[INFO]  GL_AMD_vertex_shader_layer
[INFO]  GL_AMD_vertex_shader_viewport_index
[INFO]  GL_ARB_ES3_compatibility
[INFO]  GL_ARB_arrays_of_arrays
[INFO]  GL_ARB_clear_buffer_object
[INFO]  GL_ARB_compute_shader
[INFO]  GL_ARB_copy_image
[INFO]  GL_ARB_explicit_uniform_location
[INFO]  GL_ARB_fragment_layer_viewport
[INFO]  GL_ARB_framebuffer_no_attachments
[INFO]  GL_ARB_invalidate_subdata
[INFO]  GL_ARB_multi_draw_indirect
[INFO]  GL_ARB_program_interface_query
[INFO]  GL_ARB_robust_buffer_access_behavior
[INFO]  GL_ARB_shader_image_size
[INFO]  GL_ARB_shader_storage_buffer_object
[INFO]  GL_ARB_stencil_texturing
[INFO]  GL_ARB_texture_buffer_range
[INFO]  GL_ARB_texture_query_levels
[INFO]  GL_ARB_texture_storage_multisample
[INFO]  GL_ARB_texture_view
[INFO]  GL_ARB_vertex_attrib_binding
[INFO]  GL_KHR_debug
[INFO]  GL_KHR_robustness
[INFO]  GL_KHR_texture_compression_astc_ldr
[INFO]  GL_AMD_pinned_memory
[INFO]  GL_ARB_bindless_texture
[INFO]  GL_ARB_buffer_storage
[INFO]  GL_ARB_clear_texture
[INFO]  GL_ARB_compute_variable_group_size
[INFO]  GL_ARB_enhanced_layouts
[INFO]  GL_ARB_indirect_parameters
[INFO]  GL_ARB_internalformat_query2
[INFO]  GL_ARB_multi_bind
[INFO]  GL_ARB_query_buffer_object
[INFO]  GL_ARB_seamless_cubemap_per_texture
[INFO]  GL_ARB_shader_draw_parameters
[INFO]  GL_ARB_shader_group_vote
[INFO]  GL_ARB_texture_mirror_clamp_to_edge
[INFO]  GL_ARB_texture_stencil8
[INFO]  GL_ARB_vertex_type_10f_11f_11f_rev
[INFO]  GL_EXT_shader_integer_mix
[INFO]  GL_NVX_gpu_memory_info
[INFO]  GL_ARB_ES3_1_compatibility
[INFO]  GL_ARB_clip_control
[INFO]  GL_ARB_conditional_render_inverted
[INFO]  GL_ARB_cull_distance
[INFO]  GL_ARB_derivative_control
[INFO]  GL_ARB_direct_state_access
[INFO]  GL_ARB_get_texture_sub_image
[INFO]  GL_ARB_pipeline_statistics_query
[INFO]  GL_ARB_shader_texture_image_samples
[INFO]  GL_ARB_texture_barrier
[INFO]  GL_ARB_transform_feedback_overflow_query
[INFO]  GL_EXT_polygon_offset_clamp
[INFO]  GL_EXT_shader_image_load_formatted
[INFO]  GL_KHR_blend_equation_advanced
[INFO]  GL_KHR_context_flush_control
[INFO]  GL_KHR_robust_buffer_access_behavior
[INFO]  GL_ARB_parallel_shader_compile
[INFO]  GL_ARB_shader_atomic_counter_ops
[INFO]  GL_ARB_shader_ballot
[INFO]  GL_ARB_shader_clock
[INFO]  GL_ARB_shader_viewport_layer_array
[INFO]  GL_KHR_no_error
[INFO]  GL_KHR_texture_compression_astc_sliced_3d
[INFO]  GL_EXT_window_rectangles
[INFO]  GL_MESA_shader_integer_functions
[INFO]  GL_ARB_polygon_offset_clamp
[INFO]  GL_ARB_texture_filter_anisotropic
[INFO]  GL_EXT_memory_object
[INFO]  GL_EXT_memory_object_fd
[INFO]  GL_EXT_semaphore
[INFO]  GL_EXT_semaphore_fd
[INFO]  GL_KHR_parallel_shader_compile
[INFO]  GL_AMD_framebuffer_multisample_advanced
[INFO]  GL_EXT_texture_sRGB_R8
[INFO] [GL]: Using resolution 3840x2160
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [udev]: Plugged pad: Microsoft X-Box One S pad (1118:746) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event18) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event18) supports 16 force feedback effects.
[INFO] [Autoconf]: 2 profiles found.
[INFO] [Autoconf]: selected configuration: /home/kodi/.config/retroarch/autoconfig/Microsoft X-Box One S pad.cfg
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: x11
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Menu]: Found menu display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Menu]: Found menu display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x56536c68a640
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "alsa" driver.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_image_history.lpl].
[INFO] Loading favorites file: [/home/kodi/.config/retroarch/content_favorites.lpl].
[INFO] [GL]: VSync => off
[INFO] [GLX]: glXSwapInterval(0)
[INFO] [GL]: VSync => on
[INFO] [GLX]: glXSwapInterval(1)
^C[INFO] [config] Saved new config to "/home/kodi/.config/retroarch/retroarch.cfg".
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] [PulseAudio]: Pausing.
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [XINERAMA]: Saved monitor #0.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] [Audio]: Average audio buffer saturation: 69.27 %, standard deviation (percentage points): 1.28 %.
[Audio]: Amount of time spent close to underrun: 0.00 %. Close to blocking: 0.00 %.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] [Audio]: Average audio buffer saturation: 69.27 %, standard deviation (percentage points): 1.28 %.
[Audio]: Amount of time spent close to underrun: 0.00 %. Close to blocking: 0.00 %.
```

**Comment by LazyBumHorse** [comment]
`[DEBUG] replacing version 1.-2222 with 4.6`
Yeah, that's bugged, I think this happens in #9250 as well.

**Comment by LazyBumHorse** [comment]
This is more for fun than anything: https://github.com/LazyBumHorse/RetroArch/commit/0369e822c13ac90fccee4743c436f77d2332a754
With this you should get the exact same error as with glcore.

**Comment by asavah** [comment]
Yep, gl is fixed now ))
video_driver="gl"
```
HOME=/home/kodi DISPLAY=:0 retroarch -v --log-file /dev/stdout
[INFO] RetroArch 1.7.7 (Git d4de1eaf7d)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 2400G with Radeon Vega Graphics
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AVX2 AES
[INFO] Built: Aug 11 2019
[INFO] Version: 1.7.7
[INFO] Git: d4de1eaf7d
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [DEBUG] XInitThreads()
[INFO] [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 3840x2160.
[INFO] [GLX]: Window manager is Openbox.
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [GLX]: Using Xinerama on screen #0.
[INFO] [GLX]: X = 0, Y = 0, W = 3840, H = 2160.
[INFO] [GLX]: Using true fullscreen.
[INFO] [DEBUG] replacing version 0.0 with 4.6
[INFO] [DEBUG] glx_create_context_attribs()
[WARN] [DEBUG]: message: GLXBadFBConfig, request code: 152, minor code: 34
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
retroarch: xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```

**Comment by LazyBumHorse** [comment]
Hooray! :smile:

Fun aside, thanks for the hard work testing all this, @asavah, now we at least know exactly what _isn't_ causing this.

I got a few vague ideas, one of them I can try tomorrow, but it looks like this might just not work out for Mesa.

In the worst case the error lies in Mesa/X and we have to add some nasty workaround (aka hack) like detecting Mesa, calling `glxinfo` and parsing the supported version.

**Comment by asavah** [comment]
If you need anything at runtime just ping me.

**Comment by asavah** [comment]
Jeez it's mesa bug https://bugs.freedesktop.org/show_bug.cgi?id=99781
Patch that fixes it https://gitlab.freedesktop.org/mesa/mesa/commit/e91ee763c378d03883eb88cf0eadd8aa916f7878 
however this patch was reverted due to issues with some games in wine ...

Building mesa 19.1.4 with said patch applied produces:
video_driver="glcore"
```
[INFO] RetroArch 1.7.7 (Git d4de1eaf7d)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 2400G with Radeon Vega Graphics
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AVX2 AES
[INFO] Built: Aug 12 2019
[INFO] Version: 1.7.7
[INFO] Git: d4de1eaf7d
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [DEBUG] XInitThreads()
[INFO] [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
[INFO] [GLCore]: Found GL context: x
[INFO] [GLCore]: Detecting screen resolution 3840x2160.
[INFO] [GLX]: Window manager is Openbox.
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [GLX]: Using Xinerama on screen #0.
[INFO] [GLX]: X = 0, Y = 0, W = 3840, H = 2160.
[INFO] [GLX]: Using true fullscreen.
[INFO] [DEBUG] replacing version 3.2 with 4.6
[INFO] [DEBUG] glx_create_context_attribs()
[WARN] [DEBUG]: message: GLXBadFBConfig, request code: 152, minor code: 34
[INFO] [DEBUG] XSetErrorHandler(old_handler)
[INFO] [DEBUG] failed
[INFO] [DEBUG] replacing version 4.6 with 4.5
[INFO] [DEBUG] glx_create_context_attribs()
[INFO] [DEBUG] XSetErrorHandler(old_handler)
[INFO] [DEBUG] success
[INFO] [GLX]: Found swap function: glXSwapIntervalMESA.
[INFO] [GLX]: glXSwapInterval(0)
[INFO] [GLCore]: Vendor: X.Org, Renderer: AMD RAVEN (DRM 3.32.0, 5.2.8-k1, LLVM 9.0.0).
[INFO] [GLCore]: Version: 4.5 (Core Profile) Mesa 19.1.4.
[INFO] [GLCore]: Using resolution 3840x2160
[INFO] [udev]: Plugged pad: Microsoft X-Box One S pad (1118:746) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event18) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event18) supports 16 force feedback effects.
[INFO] [Autoconf]: 2 profiles found.
[INFO] [Autoconf]: selected configuration: /home/kodi/.config/retroarch/autoconfig/Microsoft X-Box One S pad.cfg
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [GLCore]: Loading stock shader.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]:   Textures:
[INFO] [slang]:      Source (#0)
[INFO] [slang]:
[INFO] [slang]:   Uniforms (Vertex: yes, Fragment: no):
[INFO] [slang]:   Push Constants (Vertex: no, Fragment: no):
[INFO] [slang]:      MVP (Offset: 0)
[INFO] [slang]:
[INFO] [slang]:   Parameters:
[INFO] [GLCore]: Not using frame history.
[INFO] [GLCore]: Not using framebuffer feedback.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: x11
[INFO] Found shader "/usr/share/libretro/shaders/retroarch.slangp"
[INFO] Found shader "/usr/share/libretro/shaders/stock.slang"
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Menu]: Found menu display driver: "glcore".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Menu]: Found menu display driver: "glcore".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x563bc3d5a640
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "alsa" driver.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_image_history.lpl].
[INFO] Loading favorites file: [/home/kodi/.config/retroarch/content_favorites.lpl].
[INFO] [GLCore]: VSync => off
[INFO] [GLX]: glXSwapInterval(0)
[INFO] [GLCore]: VSync => on
[INFO] [GLX]: glXSwapInterval(0)
```

**Comment by asavah** [comment]
And on a side note: mesa's own glxinfo seems to use almost the same technique - query core profiles from higher to lower https://cgit.freedesktop.org/mesa/demos/tree/src/xdemos/glxinfo.c#n267 but it doesn't crash with xcb error weirdness.

**Comment by LazyBumHorse** [comment]
Alright, this scratches one of the ideas I had, so let's try a workaround (aka ugly hack)

@asavah Can you try https://github.com/LazyBumHorse/RetroArch/commit/2ddb26a5759c229f3621130ab7ed594834118e2b with glcore?

**Comment by asavah** [comment]
@LazyBumHorse I'm at work now, probably won't be able to test anything until 16:00 UTC.
I'll reply with results once I'm able to test.

**Comment by LazyBumHorse** [comment]
@asavah Yeah, no worries, take your time!

**Comment by asavah** [comment]
Done, looks good with the new patch.
I made sure I used unpatched mesa.
video_driver="glcore"
```
retroarch -v --log-file /dev/stdout
[INFO] RetroArch 1.7.7 (Git 7c78e0ad1e)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 2400G with Radeon Vega Graphics
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AVX2 AES
[INFO] Built: Aug 12 2019
[INFO] Version: 1.7.7
[INFO] Git: 7c78e0ad1e
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
[INFO] [GLCore]: Found GL context: x
[INFO] [GLCore]: Detecting screen resolution 3840x2160.
[INFO] [GLX]: Window manager is Openbox.
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [GLX]: Using Xinerama on screen #0.
[INFO] [GLX]: X = 0, Y = 0, W = 3840, H = 2160.
[INFO] [GLX]: Using true fullscreen.
[INFO] [DEBUG] version string = 4.5 (Core Profile) Mesa 19.1.4
[INFO] [GLX]: Found swap function: glXSwapIntervalMESA.
[INFO] [GLX]: glXSwapInterval(0)
[INFO] [GLCore]: Vendor: X.Org, Renderer: AMD RAVEN (DRM 3.32.0, 5.2.8-k1, LLVM 9.0.0).
[INFO] [GLCore]: Version: 4.5 (Core Profile) Mesa 19.1.4.
[INFO] [GLCore]: Using resolution 3840x2160
[INFO] [udev]: Plugged pad: Microsoft X-Box One S pad (1118:746) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event18) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event18) supports 16 force feedback effects.
[INFO] [Autoconf]: 2 profiles found.
[INFO] [Autoconf]: selected configuration: /home/kodi/.config/retroarch/autoconfig/Microsoft X-Box One S pad.cfg
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [GLCore]: Loading stock shader.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]:   Textures:
[INFO] [slang]:      Source (#0)
[INFO] [slang]:
[INFO] [slang]:   Uniforms (Vertex: yes, Fragment: no):
[INFO] [slang]:   Push Constants (Vertex: no, Fragment: no):
[INFO] [slang]:      MVP (Offset: 0)
[INFO] [slang]:
[INFO] [slang]:   Parameters:
[INFO] [GLCore]: Not using frame history.
[INFO] [GLCore]: Not using framebuffer feedback.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: x11
[INFO] Found shader "/usr/share/libretro/shaders/retroarch.slangp"
[INFO] Found shader "/usr/share/libretro/shaders/stock.slang"
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Menu]: Found menu display driver: "glcore".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Menu]: Found menu display driver: "glcore".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x55817b827640
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "alsa" driver.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/home/kodi/.config/retroarch/content_image_history.lpl].
[INFO] Loading favorites file: [/home/kodi/.config/retroarch/content_favorites.lpl].
[INFO] [GLCore]: VSync => off
[INFO] [GLX]: glXSwapInterval(0)
[INFO] [GLCore]: VSync => on
[INFO] [GLX]: glXSwapInterval(0)
[INFO] [config] Saved new config to "/home/kodi/.config/retroarch/retroarch.cfg".
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] [PulseAudio]: Pausing.
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [XINERAMA]: Saved monitor #0.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
```

**Comment by LazyBumHorse** [comment]
Time to clean it up then

**Comment by LazyBumHorse** [comment]
Not yet tested, currently writing description

**Comment by LazyBumHorse** [comment]
Missed 2 `!` and 1 `;`, tested it on Ubuntu with Nvidia, now it only needs one last test for Mesa.

@asavah Can you do the honors?

**Comment by asavah** [comment]
Everything looks good here.
Started RA with all the drivers listed below and played a few games for a minute or two,
tried a bunch of cores with heavier one like beetle_psx_hw and flycast(reicast) among others.
glcore = ok
gl= ok
vulkan = ok

@LazyBumHorse huge thanks for finding a way to fix this.

**Comment by LazyBumHorse** [comment]
@asavah Huge thanks to you, couldn't have done it otherwise!

**Comment by bparker06** [comment]
@LazyBumHorse 

```
   if (core_context || debug)
      if (core_context)
         if (!core_context)
            if (core_context)
```

Surely all but the first one should be removed?

**Comment by bparker06** [comment]
https://github.com/libretro/RetroArch/blob/010df00d74c326a130faa67440b126b38dbd62c0/gfx/drivers_context/x_ctx.c#L926

The created context leaks here, it was never destroyed before trying the higher versions.

Why not use `x_log_error_handler` for all X11 errors, all the time? Having a log message printed at all is better than not... also why was the `exit()` removed? All X11 errors with the exception of the unsupported context versions *should* constitute program-exiting behavior.

**Comment by LazyBumHorse** [comment]
> Surely all but the first one should be removed?

No, I added `if (core_context)` to
```
   attribs[1] = versions[i][0];
   attribs[3] = versions[i][1];
```
because it would garble `attribs` in the case when
```
if (core_context)
{
   *aptr++ = WGL_CONTEXT_MAJOR_VERSION_ARB;
   *aptr++ = win32_major;
   *aptr++ = WGL_CONTEXT_MINOR_VERSION_ARB;
   *aptr++ = win32_minor;
...
```
is not run.

The
```
         if (!core_context)
            version_rows = 1;
```
before the loop is a simple optimization so it doesn't loop but only does a single `pcreate_context` call.

**Comment by LazyBumHorse** [comment]
> The created context leaks here, it was never destroyed before trying the higher versions.

Good point, I need to find out how to free it.

> Why not use `x_log_error_handler` for all X11 errors, all the time? Having a log message printed at all is better than not... also why was the `exit()` removed? All X11 errors with the exception of the unsupported context versions *should* constitute program-exiting behavior.

I removed the `exit` because it was causing issues and just logging still does the job because the code does have error handling.

That said, we can still improve this later, but it's not that easy, e.g. look at the [glXCreateContextAttribsARB spec](https://www.khronos.org/registry/OpenGL/extensions/ARB/GLX_ARB_create_context.txt) and search for:
> On failure glXCreateContextAttribsARB returns NULL and generates an
    X error with extended error information. Conditions that cause
    failure include:

That's no small list of errors to catch,  and therefore lots of room for error.
I won't be doing this in this PR.

**Comment by bparker06** [comment]
>No

Ohh I missed the `|| debug` part and assumed it kept checking what was already known to always be true, my mistake.

**Comment by LazyBumHorse** [comment]
Context shouldn't leak anymore.
I'm going to bed for today, hopefully we can get this merged tomorrow.

**Comment by bparker06** [comment]
>That's no small list of errors to catch

But only the specific error I previously checked for was relevant to unsupported context versions... everything else should be an `exit()`. I had that logic in there but it was removed... that's what I don't understand. Basically main concern is not failing soon enough when something bad happens, causing hard-to-debug issues.

**Comment by LazyBumHorse** [comment]
@bparker06 Okay, I'll explain it one more time, so you'll hopefully see that this `exit` completely unneeded:

First if all: In https://github.com/libretro/RetroArch/pull/9279#issuecomment-520248086 we saw that there is a default error handler which does log and `exit` like you want it too, therefore we are only talking about this piece of code.

Now, this piece of code calls exactly 2 function which could generate an X error, `glx_create_context_attribs` and `glXMakeContextCurrent` (and the latter only in the Mesa workaround)

Let's look at `glx_create_context_attribs` first.
It is guaranteed to return `NULL` in case it raises an error as we saw in the spec and let's look at what happens then, shall we?

It'll reach this point
https://github.com/libretro/RetroArch/blob/116ed81c238b3061cf8c8a111fcf0ec933fa86fb/gfx/drivers_context/x_ctx.c#L942-L946
clean up and return false
https://github.com/libretro/RetroArch/blob/116ed81c238b3061cf8c8a111fcf0ec933fa86fb/gfx/drivers_context/x_ctx.c#L1057
If using glcore, it was called from `gl_core_get_context` here
https://github.com/libretro/RetroArch/blob/116ed81c238b3061cf8c8a111fcf0ec933fa86fb/gfx/drivers/gl_core.c#L509-L511
which gets returned and checked here
https://github.com/libretro/RetroArch/blob/116ed81c238b3061cf8c8a111fcf0ec933fa86fb/gfx/drivers/gl_core.c#L962-L966
which will make the video driver `init` return `NULL`
https://github.com/libretro/RetroArch/blob/116ed81c238b3061cf8c8a111fcf0ec933fa86fb/gfx/drivers/gl_core.c#L1135
The `init` is called and checked from here
https://github.com/libretro/RetroArch/blob/116ed81c238b3061cf8c8a111fcf0ec933fa86fb/retroarch.c#L16920-L16928
which then calls
https://github.com/libretro/RetroArch/blob/116ed81c238b3061cf8c8a111fcf0ec933fa86fb/retroarch.c#L16988-L16989
which is here
https://github.com/libretro/RetroArch/blob/116ed81c238b3061cf8c8a111fcf0ec933fa86fb/retroarch.c#L22705-L22721

I like to point out the description
> Sanely kills the program.

because calling `exit` is the exact opposite.
We need to release system resources first and the code does that when you let it.

So what's left?
The `glXMakeContextCurrent` call which was added in the Mesa workaround.
Here's the [spec](https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glXMakeContextCurrent.xml), it might generate errors and the return value is not checked, so this is the one and only thing that could cause any kind of issue.
But not really.
Because if `glXMakeContextCurrent` fails, the following `glGetString` will also fail.
It'll actually dereference a null pointer and since this is practically guaranteed to crash, it's like it's calling `exit`.
I can add a null pointer check if you want, with that it would then fail either in the version loop like in the case above or in the following `glXMakeContextCurrent` which is protected by the default error handler.

**Comment by bparker06** [comment]
>there is a default error handler which does log and exit like you want it to

where? the only exit I see is the new one I added in current master, which this PR removes here: https://github.com/libretro/RetroArch/pull/9279/files#diff-47a5a2cb0befff4022ace7037dfca292L189

Maybe I'm just misunderstanding something. Either way this should be ok to merge anyway.

**Comment by LazyBumHorse** [comment]
We tested [a version without a `XSetErrorHandler` call](https://github.com/LazyBumHorse/RetroArch/commit/6c85d9b17770b9a48c47982fdc6d4b12affe5e3b#diff-47a5a2cb0befff4022ace7037dfca292L866), again, [link to the comment](https://github.com/libretro/RetroArch/pull/9279#issuecomment-520248086). This was the output:

> stderr output
> 
> ```
> X Error of failed request:  GLXBadFBConfig
>   Major opcode of failed request:  152 (GLX)
>   Minor opcode of failed request:  34 ()
>   Serial number of failed request:  76
>   Current serial number in output stream:  75
> ```

After adding the `XSetErrorHandler`, it would be replaced.

**Comment by bparker06** [comment]
I guess it's time for me to give up as I'm just not really understanding this part of the discussion. No worries.
