### PR TITLE
apply disconnect logic for COMMAND_MEMORY_READ / COMMAND_MEMORY_WRITE

### LINKED ISSUE #13664: READ_CORE_MEMORY etc acts upon the wrong location if core's memory descriptor is non-contiguous
## Description

Cores tell RetroArch about the emulated system memory using SET_MEMORY_MAPS. The emulated system memory can then be accessed by other programs communicating with RetroArch over the UDP Network Commands, without further participation from the core which owns the memory.

Cores may use a large, contiguous buffer, to back an area of emulated system memory that can be accessed non-contiguously in emulation.

In such cores, the core may indicate specific address bits that RetroArch should "disconnect" when translating from the emulated address space to the internal buffer. These bits are specified in the `disconnect` field of a `retro_memory_descriptor`.

Trivial example:
The memory descriptor could describe a "disconnect" of 0x0f0 - bits 4-7 are disconnected.
Emulated address space address: xxxx yyyy zzzz (such as 0x123) maps to an offset in the backing buffer of: xxxx zzzz (0x13).

Bug: The "disconnect" bits are not being honored: RetroArch's READ_CORE_MEMORY handler is attempting to read from 0x123 in the core's backing buffer instead of from 0x13.

Possible cause:

The correct memory descriptor is being retrieved, but then `command_memory_get_pointer()` in command.c ignores the `desc->disconnect` field (representing disconnected memory addressing bits). It instead assumes that the emulated address space covered by the memory descriptor is contiguous. Actually, only the host system storage `desc->ptr` must be contiguous for a given descriptor.

### Expected behavior

Can correctly read any part of the SNES ROM using READ_CORE_MEMORY.

### Actual behavior

The wrong bank's data is being returned unless the first bank (ROM: Bank $80) is requested.

Writable memory may also be accessed non-contiguously in SNES, so WRITE_CORE_MEMORY is likely affected as well, and could be demonstrated if so.

### Steps to reproduce the bug

1. Hex edit a SNES/SFC ROM that uses [SNES LoROM memory mapping](https://en.wikibooks.org/wiki/Super_NES_Programming/SNES_memory_map). Overwrite with some demonstration data (emulated system may crash; that's OK as access to the data from outside doesn't change. Alternatively, you could instead compare the UDP API's result against the ROM's existing data, but sometimes the start of each bank is very similar so pay close attention).
- ROM file offset  0x8000 = Overwrite with 0xBA, 0x81 // our indicator for "bank $81"
- ROM file offset 0x10000 = Overwrite with 0xBA, 0x82 // our indicator for "bank $82"

2. Load the ROM using a SNES core that implements SET_MEMORY_MAPS (and therefore supports READ_CORE_MEMORY), such as bsnes-mercury. The following descriptor, or similar, is reported by the core, as seen with core debug logging enabled:
```
[INFO] [Environ]: SET_MEMORY_MAPS.
[INFO]            ndx flags  ptr              offset   start    select   disconn  len      addrspace
[INFO]            016 M1A1bC 0000019bfbfde040 00000000 00808000 00808000 00008000 00300000
```

3. retroarch.cfg or set in UI: network_cmd_enable=true

4. Execute commands over the UDP Network Commands port (default 55355):

READ_CORE_MEMORY 808000 2
Expected behavior: RetroArch replies with the first 2 bytes of the ROM, which in SNES native terms are accessed at $80:8000.
Actual: As expected.

READ_CORE_MEMORY **81**8000 2
Expected behavior: RetroArch replies with the first 2 bytes of bank $81 ROM space (SNES-native address: $81:8000): BA 81
Actual: (Bug) RetroArch replies with BA **82** // our indicator for "bank $82".

Examining further:
- Operations upon Bank $81 are being directed to Bank $82
- Operations upon Bank $82 are being directed to Bank $84
- ...
- Operations upon Bank $AF are being directed to Bank $DE
- Operations upon the latter half of the ROM are failing with "-1 no data for descriptor"
(Latter half of the ROM would be Bank $B0 onward, given a 3MiB ROM file, whose last bank would be Bank $DF)

### Bisect Results

This appears to have been broken since READ_CORE_MEMORY and WRITE_CORE_MEMORY were implemented (in RetroArch 1.9.2).

### Version/Commit

- RetroArch: ee4486068d

### Environment information

- OS: Windows 10
- Compiler: MinGW 64-bit

### PR DESCRIPTION
**Pull request by Jamiras**
## Description

Adds `disconnect` support to `READ_CORE_MEMORY` and `WRITE_CORE_MEMORY` network commands.

ROM data slices:
image

After (correct):
```
$ echo -n "READ_CORE_MEMORY 808000 2" | nc -u -w1 localhost 55355
READ_CORE_MEMORY 808000 78 9C
$ echo -n "READ_CORE_MEMORY 818000 2" | nc -u -w1 localhost 55355
READ_CORE_MEMORY 818000 00 00
$ echo -n "READ_CORE_MEMORY 828000 2" | nc -u -w1 localhost 55355
READ_CORE_MEMORY 828000 00 00
$ echo -n "READ_CORE_MEMORY 838000 2" | nc -u -w1 localhost 55355
READ_CORE_MEMORY 838000 4C 15
$ echo -n "READ_CORE_MEMORY 848000 2" | nc -u -w1 localhost 55355
READ_CORE_MEMORY 848000 0B A9
$ echo -n "READ_CORE_MEMORY 858000 2" | nc -u -w1 localhost 55355
READ_CORE_MEMORY 858000 9C DC
$ echo -n "READ_CORE_MEMORY 868000 2" | nc -u -w1 localhost 55355
READ_CORE_MEMORY 868000 00 3C
```

Before (incorrect):
```
$ echo -n "READ_CORE_MEMORY 818000 2" | nc -u -w1 localhost 55355
READ_CORE_MEMORY 818000 00 00    # this is actually ROM data at $10000
$ echo -n "READ_CORE_MEMORY 828000 2" | nc -u -w1 localhost 55355
READ_CORE_MEMORY 828000 0B A9    # this is actually ROM data at $20000
$ echo -n "READ_CORE_MEMORY 838000 2" | nc -u -w1 localhost 55355
READ_CORE_MEMORY 838000 00 3C    # this is actually ROM data at $30000
```

## Related Issues

Fixes #13664

## Related Pull Requests

n/a

## Reviewers

@strotlog

### CODE REVIEW

File: command.c [hunk 1]
```diff
@@ -694,15 +694,37 @@ static const rarch_memory_descriptor_t* command_memory_get_descriptor(const rarc
...
             return desc;
+         }
       }
       else
       {
          /* otherwise, attempt to match the address by matching the select bits */
          if (((desc->core.start ^ address) & desc->core.select) == 0)
          {
+            /* adjust the address to the start of the descriptor */
+            unsigned desc_offset = address - (unsigned)desc->core.start;
```
Comment (strotlog) [inline command.c:708]: I think there is an assumption here that the translation from emulated address to backing buffer address is "distributive". Currently, the main part of this translation, is the disconnect aka mmap_reduce function, so distributiveness would mean that:
```
mmap_reduce((address - start), disconnect) ==
mmap_reduce(address, disconnect) - mmap_reduce(start, disconnect)
```

However, this is not not mathematically true (even though equality does seem to be satisfied for the SNES example case). Counterexample:

```
          start    select   disconn      address
          81800    80800    0f0f0        90800
0x000 == mmap_reduce((address - start), disconnect)
 vs.
0x110 == mmap_reduce(address, disconnect) - mmap_reduce(start, disconnect)
```

Comment (Jamiras) [reply command.c:708]: That seems logical, but this implementation matches the original implementation that you referenced: https://github.com/libretro/RetroArch/blob/v1.9.0/cheevos/fixup.c#L235-L239

I didn't include the additional masking as `disconnect_mask` was calculated from the `desc->core.len`, presumably to ensure the values didn't exceed the provided buffer. The direct check against `len` should satisfy that constraint, and was also present in the previous code after the mmap_reduce call.

Also, I find it hard to imagine that a starting address would have bits set that aren't part of the `select` mask.  If you change `start` to match `select` in your example, both values come out the same:
```
          start    select   disconn      address
          80800    80800    0f0f0        90800
0x100 == mmap_reduce((address - start), disconnect) // 90800-80800 = 10000 => reduce to 100
 vs.
0x100 == mmap_reduce(address, disconnect) - mmap_reduce(start, disconnect) // reduced: 980-880 = 100
```

The discrepancy does still exist if `select` and `disconnect` overlap:
```
          start    select   disconn      address
          81800    81800    0f0f0        90800
0x000 == mmap_reduce((address - start), disconnect) // 90800-81800 = 0F000 => reduce to 000
 vs.
0x100 == mmap_reduce(address, disconnect) - mmap_reduce(start, disconnect) // reduced: 980-880 = 100
```

But even with an awkward `start`, a more logical `disconnect` works:
``` 
          start    select   disconn      address
          81800    81800    0e0f0        90800
0x100 == mmap_reduce((address - start), disconnect) // 90800-81800 = F000 => reduce to 100
 vs.
0x100 == mmap_reduce(address, disconnect) - mmap_reduce(start, disconnect) // reduced: 1280-1180 = 100

          1001 0000 1000 0000 0000 address
          0000 1110 0000 1111 0000 disconn
          1001    0 1000      0000 => 1 0010 1000 0000 => 1280

          1000 0001 1000 0000 0000 start
          0000 1110 0000 1111 0000 disconn
          1000    1 1000      0000 => 1 0001 1000 0000 => 1180
```

Your proposal does seem like it would handle more abstract cases, but this matches the old behavior, and has already been merged. Do you think this is worth opening another PR?

Comment (strotlog) [reply command.c:708]: Good point, the implementation does match the behavior from 1.9.0, which may not have had any issues reported. (I only noticed this math oddity when reading the new code - probably because the new variable names are clearer!)

I also wasn't able to invent a plausible example that would exhibit this issue in a reasonable amount of time. Thank you for looking for one as well.

I'm OK with the fix as-is. By the way, my testing looks good too.
