### PR TITLE
only wait for save task to complete

### LINKED ISSUE #10943: Auto Save State freezes RetroArch while Cheevos is enabled
## Description

Confirmed to be an issue for Beetle Lynx, Mesen, FCEUmm, and BSNES Mercury Balanced cores.

All three worked fine before (version 1.8.8) Now they freeze on exit.

[What you expected to happen]

I expect to have 'Auto Save State' enabled, and have Cheevos enabled/my username and password filled out, and exit a game with the exit hotkey, and cleanly exit RetroArch with a save state.

### Actual behavior

When you try to exit while running a game with the both the Mesen and FCEUmm cores, RetroArch freezes.

### Steps to reproduce the bug

1. On a fresh install of RetroArch, open RetroArch, and go to settings/saving/Auto Save, and turn it on.
2. Go to settings/Achievements, turn on Achievements, and fill out your Username and Password.
2. Save your configuration.
3. Run a game with the Mesen  or FCEUmm cores.
4. Try to exit, with the exit hotkey - RetroArch freezes.

### Version/Commit
RetroArch 1.8.9, the latest stable version - but I also just tested with the latest nightly (6-29-20), and the issue is still present.

### Environment information

- OS: Windows 10

### LINKED ISSUE #11004: RetroAchievments + Auto-Save/Load = Freeze
## Description
When I activate RetroAchievments (log in) and activate auto-saving/loading-feature RetroArch freezing when I exit the game (Games with Achievments).

This happens when the command line is executed.

Example:
/usr/bin/retroarch -v -L /tmp/cores/snes9x_libretro.so --config /storage/.config/retroarch/retroarch.cfg "/storage/roms/snes/Super Mario All-Stars (USA).zip"

### Expected behavior
No freeze and auto-savestate

### Actual behavior
System freeze

### Steps to reproduce the bug
1. Activate Wifi
2. RetroAchievments login
3. Activate Auto-Save/Loading Feature in the "Settings"/"Saving" menu
4. Start a game with Achievments like Super Mario All-Stars
5. Exit the game -> Freeze happens

### Bisect Results
With 1.8.8. this combination works but not with 1.8.9 
Without RetroAchievments Auto-save/load works fine.
Or RetroAchievments activated but auto-save/load off works also fine.

### Version/Commit
Build date: Jul 8 2020
Git Version: d748b37e6b

### Environment information
Device: Odroid Go Advance
OS: EmuELEC 3.6 (and latest Test-Release)
https://github.com/EmuELEC/EmuELEC
https://github.com/EmuELEC/EmuELEC-tests/releases

### PR DESCRIPTION
**Pull request by Jamiras**
## Description

Reimplements https://github.com/libretro/RetroArch/commit/6083450d4e2c49da74d0c4a4a1a4833a2a6a66fa such that it only waits for the save task to complete instead of all tasks. Waiting for all tasks with achievements enabled would cause it to wait indefinitely as there was always a task scheduled to send rich presence information to the server. I've also updated the wait for all tasks logic to ignore scheduled tasks.

## Related Issues

fixes #10943
fixes #11004

## Related Pull Requests

n/a

## Reviewers

@twinaphex

### CODE REVIEW

File: libretro-common/queues/task_queue.c [hunk 1]
```diff
@@ -420,10 +420,9 @@ static void retro_task_threaded_wait(retro_task_condition_fn_t cond, void* data)
       retro_task_threaded_gather();
 
       slock_lock(running_lock);
-      wait = (tasks_running.front) &&
-             (!cond || cond(data));
+      wait = (tasks_running.front && !tasks_running.front->when);
       slock_unlock(running_lock);
-   } while (wait);
+   } while (wait && (!cond || cond(data)));
```
Comment (Jamiras) [inline libretro-common/queues/task_queue.c:425]: I had to move the callback out of the lock as the callback also needs to acquire the lock to validate whether the task is still in the queue. (pthread_mutex is not re-entrant without some additional setup). Besides, it's generally not wise to have callbacks inside a lock as you don't know how long the callback will take and want to release the lock as quickly as possible.

**Comment by twinaphex** [comment]
@jdgleaver Can you review this?

**Comment by jdgleaver** [comment]
@Jamiras Nice - thank you for this!

My only slight concern is the fact that the callback is no longer locked. I can see that the change is required in this case, and there is no existing usage of `task_queue_wait()` where this would be a problem - but I guess the original intention was that the callback could potentially make use of task data in some fashion, and now that's not really possible.

I think the PR is good, though, and should be merged as-is - but would you mind adding a comment to the definition of `task_queue_wait()` in `task_queue.h`, explaining that:

- The wait only applies to running tasks, not scheduled ones
- The callback function is not handled in a fashion that is inherently thread-safe, and therefore shouldn't be granted direct access to anything used in the task thread

I don't think these 'limitations' are any sort of problem at all, but it would be good to give future devs proper warning to prevent accidental data races :)

**Comment by Jamiras** [comment]
> I guess the original intention was that the callback could potentially make use of task data in some fashion, and now that's not really possible.

Using any of the `task_set_` functions to modify the task will still use the `property_lock`. The `task_get_` functions use both `running_lock` and `property_lock` (I'm not sure if that's intentional, or what the distinction is). Anything that was using `running_lock` would not have previously been callable from the callback.

> adding a comment [...] explaining that:
> * The callback function is not handled in a fashion that is inherently thread-safe, and therefore shouldn't be granted direct access to anything used in the task thread

I don't believe there's any need to document this. The comment already says the callback is only used to "return early":

> Will return early if cond is not NULL and cond(data) returns false.

The task object itself is protected if the caller uses the `task_` functions instead of accessing it directly as described earlier.

The `running_lock` that used to be around the callback is primarily used for moving things in and out of the `tasks_running` queue. `task_queue_wait` simply looks to see if the `tasks_running` queue is non-empty, and only calls the callback to see if it should continue to wait if it is not empty. 

Moving the callback outside of the lock allows the queue to become empty while the callback is being called, but as it's just an early return, it doesn't matter what the callback does as the loop will exit normally after the callback completes. The callback shouldn't assume any given task exists in the queue as the wait is for _any_ task. Therefore, any logic in the callback must work whether or not a specific item is in the queue.

I have updated the comment to indicate the function only waits for non-scheduled tasks.

**Comment by jdgleaver** [comment]
Okay, I guess I was considering potential usage scenarios (i.e. attempting to bypass the `task_` functions) that will never happen :)

This is all fine, then. Thank you again for the fix.

@twinaphex Can we please merge?

**Comment by twinaphex** [comment]
Alright, if you're in favor of it then I'll comply.
