### PR TITLE
(Win32) Remove black margins with borderless non-fullscreen window

### LINKED ISSUE #6284: When "video_window_show_decorations" and "ui_menubar_enable" are both set to false, a black margin is added to the right and top
## Description

When "video_window_show_decorations" and "ui_menubar_enable" are both set to false, a black margin is added to the right and top of the window:

unknown

### Expected behavior

The black margin shouldn't exist, like when the "ui_menubar_enable" setting is set to true.

### Actual behavior

Black margin is added.

### Steps to reproduce the bug

1. Set "video_window_show_decorations" and "ui_menubar_enable" to false.
2. Start RetroArch

### Bisect Results

It started happening after committing https://github.com/libretro/RetroArch/pull/6281

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.0 Nightly
- Git version: 4d1090dc53

### Environment information

- OS: Win 8.1
- Compiler: Buildbot

### PR DESCRIPTION
**Pull request by andersstorhaug**
## Description

On Windows, when `video_window_show_decorations` and `ui_menubar_enable` are both false, black margins are added to the window. Example image below pulled from the related issue.

Example

This happened because the window is created before setting the `WS_POPUP` style, resulting in an incorrectly recorded size for the client area.

With these changes, for borderless non-fullscreen windows the `WS_POPUP` style is used at time of window creation.

Some notes:
- A side-effect to this change is that `video_window_show_decorations` is no longer guarded by the `HAVE_WINDOW_TRANSP` macro. Seems that `WS_POPUP` was around even with Win 3.1.
- When decorations are hidden, the window will no longer have default placement from Windows and will instead be placed in the top left of the screen. Per [MS Docs](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowa#parameters), `CW_USEDEFAULT` only has effect on overlapped windows (eg with a titlebar and borders). Saved window positions still work as expected if enabled . This top-left behavior only happens on startup when borderless and there is no saved position.

## Related Issues

Fixes #6284.

### CODE REVIEW

File: gfx/common/win32_common.c [hunk 1]
```diff
@@ -2173,13 +2169,21 @@ void win32_set_style(MONITORINFOEX *current_mon, HMONITOR *hm_to_use,
       rect->right     = *width;
       rect->bottom    = *height;
 
+      bool window_show_decor = settings->bools.video_window_show_decorations;
```
Comment (LibretroAdmin) [inline gfx/common/win32_common.c:2172]: Hi, can you declare this variable at the top of the code block? This will otherwise create C89 build errors. Thanks.

**Review by LibretroAdmin — CHANGES_REQUESTED** [review]

File: gfx/common/win32_common.c (hunk 1 above)
Comment (andersstorhaug) [reply gfx/common/win32_common.c:2172]: Will do.

Comment (andersstorhaug) [reply gfx/common/win32_common.c]: Done - rebased/squashed.

**Review by LibretroAdmin — APPROVED** [review]
