### PR TITLE
Content downloader: Allow for spaces (and other characters) in directory names

### LINKED ISSUE #7056: (Menu) Content Downloader cannot load any directories with spaces
## Description

Going into any of the Content Downloader entries that have a space result in "No entries to display"

### Expected behavior

Entries should display

### Actual behavior

Entries do not display

### Steps to reproduce the bug

1. Open RetroArch
2. Online Updater
3. Content Downloader
4. Select any entry with space

### Version/Commit
You can find this information under Information/System Information

- RetroArch: v1.7.3 -- 50b23d6572

### Environment information

- OS: Arch Linux
- Compiler: GCC

### PR DESCRIPTION
**Pull request by cold-brewed**
## Description

Fixes the issue of the content downloader not being able to load directories with spaces. 

This also fixes a malformed request in `action_ok_download_generic()`.

This should make the downloader a lot less touchy about the names of directories it has to deal with. I successfully tested this by pointing the content downloader to a local server. 

## Related Issues

Fixes #7056

## Reviewers

Since it touches some networking and menu code I'd like for @fr500 or @bparker06 to give it a look.

### CODE REVIEW

File: menu/cbs/menu_cbs_ok.c [hunk 1]
```diff
@@ -3676,7 +3679,11 @@ static int action_ok_download_generic(const char *path,
    transf->enum_idx = enum_idx;
    strlcpy(transf->path, path, sizeof(transf->path));
 
-   net_http_urlencode_full(s3, s2, sizeof(s));
+   if (string_is_equal_fast(path, s, sizeof(path))) {
```
Comment (bparker06) [inline menu/cbs/menu_cbs_ok.c]: `string_is_equal_fast()` is only safe when the size is known for both strings and the specified size is guaranteed not to be larger than either. So in this case, since the length of `path` is not known, we should use the regular `string_is_equal()` or it will cause a buffer overflow.

Except it probably won't even get that far because the size parameter has been set to the size of a pointer.

Comment (cold-brewed) [reply menu/cbs/menu_cbs_ok.c]: Doh... exactly right. And only happened to work because the comparison needed was just under pointer size. Fixing.

**Comment by RobLoach** [comment]
I made the `Atari - 2600` folder have spaces again for testing.

**Comment by cold-brewed** [comment]
@RobLoach I was able to view the `Atari - 2600` directory with this fix.

**Comment by RobLoach** [comment]
That worked! Nicely done :+1:
