### PR TITLE
Prevent uninitialized memory when searching for serial in database.

### LINKED ISSUE #16906: The "Scan Directory" function does not work well with some ISO images
## Description

After selecting the "Scans a directory for content that matches the database" function and specifying the folder with games, the application analyzes the contents of one of the ISO images in the folder for hours.

### Expected behavior

If the file analysis takes more than a certain amount of time (for example, 10 seconds), the "Skip" button appears. Or, the file is skipped, but after the scan is complete, the user is notified with a list of skipped files.

### Actual behavior

Unfortunately, the application window does not display the full path to the file, and its name appears in the subfolders of the specified folder several dozen times. The scanning sequence remained a mystery to me, because the log displays files in a chaotic order.

The log shows other iso files, so the problem is not with processing all iso files, but only certain ones.

### Steps to reproduce the bug

1. Install RetroArch and download four cores: DOS (DOSBox-core), DOS (DOSBox-Pure), DOS (DOSBox-SVN) and Sinclair - ZX Spectrum (Fuse).
2. Select Import Content in the left panel, then Scan Directory. Specify the folder with the problematic ISO file.
3. Wait a few hours, making sure that the application does not complete the scanning process, displaying something like `1220/47559: image.iso.. 3%`.

### Version/Commit

RetroArch Version: 1.19.1
Git Version: 427e3fa6f6
Build Date: Jun 5 2024

- RetroArch: [version/commit]

### Environment information

- Microsoft Windows 10.0.19045.4780
- Compiler: MinGW (10.2.0) 64-bit

```
CPU Model: Intel Core i7-3770K CPU @ 3.50GHz
CPU Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX
CPU Architecture: x64
CPU Cores: 8
Frontend Identifier: Win32
Frontend OS: Windows 8 x64 Build 9200 (v6.2)
Memory: 15255/32711 MB
Power Source: 0% (No Source)
Video Context Driver: N/A
Display Width (mm): 797.00
Display Height (mm): 333.00
Display DPI: 109.00
LibretroDB Support: Yes
Overlay Support: Yes
Command Interface Support: Yes
Network Command Interface Support: Yes
Network Controller Support: Yes
Cocoa Support: No 
PNG (RPNG) Support: Yes
JPEG (RJPEG) Support: Yes
BMP (RBMP) Support: Yes
TGA (RTGA) Support: Yes
SDL 1.2 Support: No 
SDL 2 Support: Yes
Vulkan Support: Yes
Metal Support: No 
OpenGL Support: Yes
OpenGL ES Support: No 
Threading Support: Yes
KMS/EGL Support: No 
udev Support: No 
OpenVG Support: No 
EGL Support: No 
X11 Support: No 
Wayland Support: No 
XVideo Support: No 
ALSA Support: No
OSS Support: No
OpenAL Support: No
OpenSL Support: No
RSound Support: No
RoarAudio Support: No
JACK Support: No
PulseAudio Support: No
CoreAudio Support: No
CoreAudio V3 Support: No
DirectSound Support: Yes
WASAPI Support: Yes
XAudio2 Support: Yes
zlib Support: Yes
7zip Support: Yes
Dynamic Library Support: Yes
Dynamic Runtime Loading of libretro Library: Yes
Cg Support: No
GLSL Support: Yes
HLSL Support: Yes
SDL Image Support: No
FFmpeg Support: Yes
mpv Support: No
CoreText Support: No
FreeType Support: Yes
STB TrueType Support: Yes
Netplay (Peer-to-Peer) Support: Yes
Video4Linux2 Support: No 
libusb Support: No
```

[Logs](https://drive.google.com/drive/folders/1sfxKy1OB-oVWdmep6XNXUfhs5TRS2-wP)

### PR DESCRIPTION
**Pull request by zoltanvb**
## Description

When serial can not be retrieved from the image (length is 0), the translation for the database search syntax may return uninitialized memory, resulting in bogus database hits (which are not written to playlist), but also in endless scanning.

Scanning one such image was failing (running endlessly) at least once in ten tries, with the modification, the endless scan can not be reproduced any more.

## Related Issues

Closes #16906 (most probably). Maybe also #10876 , as the trace also points to serial scanning.

### CODE REVIEW

**Comment by sonninnos** [comment]
Why not just clear the var always without the if before the for loop?

**Comment by zoltanvb** [comment]
Sure, why not.

File: database_info.c [hunk 1]
```diff
@@ -496,8 +496,11 @@ char *bin_to_hex_alloc(const uint8_t *data, size_t len)
    if (len && !ret)
       return NULL;
 
+   ret[len * 2] = '\0';
```
Comment (sonninnos) [inline database_info.c]: Surely we want `[0]` like it was earlier and not `[len * 2]`..?

Comment (zoltanvb) [reply database_info.c]: Functionally equivalent since if len>0, the snprintf's will anyway overwrite it. It can also be avoided by using calloc instead of malloc. But whichever is easier to read.
