### PR TITLE
WIP: Fixes #2026 Screensaver suspend on Linux via Dbus

### LINKED ISSUE #2026: Linux screensaver suspend malfunctioning
My experience is that that the Linux screensaver suspension doesn't work properly.

**Observed behavior:** Display is prevented from blanking, but the screen still fades to black and is locked after 10 minutes when running Retroarch. Additionally, after quiting Retroarch, display blanking is still disabled (I have to run `xset dpms 300` to restore).

**Expected behavior:** Display blanking / screen locking is "suspended" (poor choice of term there) while I am running Retroarch, and is restored when I quit Retroarch.

**Setup:** Retroarch (git) under Gnome 3 Shell on Arch Linux with Gnome set to suspend the display and lock the screen after 5 minutes of inactivity.

More investigation is needed. It's possible that this is a bug in some other package such as Gnome Screensaver itself. I'll follow up with more info and hopefully a recommendation.

## Related issues

 * #30, #33
 * #1349

### PR DESCRIPTION
**Pull request by nguillaumin**
One some systems (tested with Gnome 3 on Arch Linux) the current method
of using `xdg-screensaver` to suspend the screensaver does not work.
Instead, using DBus to issue an `Inhibit` request is recommended.

The request returns a cookie that needs to be re-used to un-inhibit the
screensaver later. Additionally if the DBus connection is closed the
current inhibition is discarded. Thus, the DBus connection needs to stay
connected for the duration of the screenshot inhibition.

The code is heavily inspired from the [SDL 2.x
code](http://hg.libsdl.org/SDL/file/default/src/core/linux/SDL_dbus.c#l172).
I didn't call the SDL 2 code though since this it to fix the issue with
the GL driver, and I assume one would want to have screensaver inhibited
even when SDL 2 is not available (but GL is).

I've set "WIP" because:
* I haven't done C in a long time so my code is probably not great
* There's a dependency on DBus which I don't know is acceptable or
not
* I've put my code where I could to check it works, but `x11_common` may
not be the best place
* The code need and "init" and "deinit" kind of method as it needs to
initialise the DBus connection, and on deinit close it properly. I've
used `x11_connect` and `x11_window_destroy` but they don't sound like
the best choices.
* I'm a bit unclear as to what happens when "suspend screensaver" is
ticked on/off in the menu. This doesn't seem to call
`x11_suspend_screensaver` everytime, so I'm not sure if there's a hook
somewhere (as disabling screensaver suspend in the menu should cause a
DBus unhinibit request to be sent).
* Should I just call the SDL 2.x code (meaning that the GL driver would
depend on SDL 2.x at runtime)?

So, first of all are you ok with the approach, and if yes I'd gladly get
feedback about the code, how to architecture it and the best place to
put it.

Thanks!

### CODE REVIEW

**Comment by orbea** [comment]
gnome3 is well known for sucking at this, I don't think a dbus dependency is a good idea for something that the gnome devs should fix. `xdg-screensaver` works well with xscreensaver.

**Comment by nguillaumin** [comment]
Well, `xdg-screensaver` is using DBus under the hood with Gnome, so it seems DBus is the way to go. It doesn't work though because I think it supports only Gnome 2, not 3. 

In any case it wouldn't work anyway as a one-shot script because the DBus connection need to be maintained during screensaver inhibition (which kind of make sense, if the process dies you want the inhibition to be cancelled I think).

Also note that I'm using the generic `org.freedesktop.ScreenSaver` namespace so it should also work with other desktop environments (and possibly the `xdg-screensaver` method can be removed ultimately - I'm not even sure it still works with recent version of KDE / XFCE / ...).

**Comment by orbea** [comment]
Then why not fix `xdg-screensaver` to support gnome3? The old method should not be removed as its still very useful for anyone running just a window manager and xscreensaver and there are people who remove dbus altogether from their systems.

Anyways, if this was going to be added I think you should also add it to `qb/config.params.sh` too so that this can be set during configure. I would suggest it be off by default and only used for those that actually want it.

**Comment by t-paul** [comment]
What's with the Gnome3 bashing? Ì'm running Gnome3 on Debian/testing and `xdg-screensaver` works just fine.
And yes, `xdg-screensaver` does work as single call as it passes the window ID of RetroArch, so it will cancel the inhibit as soon as that window goes away.

**Comment by orbea** [comment]
It was not gnome3 bashing, but its a well documented reality that at least some programs have problems with disabling a screensaver in gnome3.  (i.e. https://github.com/mpv-player/mpv/issues/2063 https://bugs.archlinux.org/task/45690)

Also, maybe debian has added some patches to gnome3 to fix this while arch has not?

**Comment by twinaphex** [comment]
If this is an optional compile-time dependency then I'm fine with it.

**Comment by Alcaro** [comment]
> \+    if (dbus_connection != NULL)
> \+    {
> \+
> \+        DBusMessage *msg = dbus_message_new_method_call("org.freedesktop.ScreenSaver",

You sure you want to do that if it was never suspended?

> \+    if (!enable)
> \+       return;

That should uninhibit, not get ignored.

> \+void x11_suspend_screensaver_xdg_screensaver(Window win, bool enable);
> \+#ifdef HAVE_DBUS
> \+void x11_suspend_screensaver_dbus(bool enable);
> \+#endif

Should be static. If you want the dispatcher function above the implementations, prototypes work fine.

> \+    x11_suspend_screensaver_xdg_screensaver(wnd, enable);
> \+#ifdef HAVE_DBUS
> \+    x11_suspend_screensaver_dbus(enable);
> \+#endif

You sure we want to call both of those? ...maybe we do.

Plus everything orbea said.

**Comment by nguillaumin** [comment]
Thanks for the feedback. Who would have know that would be that controversial, eh! :wink: 

> What's with the Gnome3 bashing? Ì'm running Gnome3 on Debian/testing and xdg-screensaver works just fine.

Interesting. I agree that if  `xdg-screensaver` is supposed to work with Gnome 3, then yeah we should fix it there. I'll have a look if I can track down the problem on my install.

File: gfx/common/x11_common.c [hunk 1]
```diff
@@ -147,6 +153,75 @@ void x11_set_window_attr(Display *dpy, Window win)
...
+       return;
+
+    if (dbus_screensaver_cookie > 0)
+        return; // Already suspended
+
+    if (dbus_connection == NULL)
+        return; // DBus connection was not obtained
+
+    
+    msg = dbus_message_new_method_call("org.freedesktop.ScreenSaver",
```
Comment (nguillaumin) [inline gfx/common/x11_common.c]: > You sure you want to do that if it was never suspended?

Not sure what you mean? Is that related to checking the `enabled` flag?

File: gfx/common/x11_common.c [hunk 2]
```diff
@@ -147,6 +153,75 @@ void x11_set_window_attr(Display *dpy, Window win)
...
+}
+
+#ifdef HAVE_DBUS
+void x11_suspend_screensaver_dbus(bool enable)
+{
+    const char *app = "RetroArch";
+    const char *reason = "Playing a game";
+    DBusMessage *msg, *reply;
+
+    if (!enable)
```
Comment (nguillaumin) [inline gfx/common/x11_common.c]: > That should uninhibit, not get ignored.

Fair enough, as I said in the comments I was not too sure how the menu option work for enabling / disabling screensaver and if that function gets call with `enabled == false`. I thought I tested it and changing the setting in the menu did not call this function again, but I may be wrong.

Also, I took that straight from the `xdg-screensaver` method, so presumably it suffers from the same issue.

File: gfx/common/x11_common.h [hunk 3]
```diff
@@ -44,6 +44,10 @@ void x11_save_last_used_monitor(Window win);
 void x11_show_mouse(Display *dpy, Window win, bool state);
 void x11_windowed_fullscreen(Display *dpy, Window win);
 void x11_suspend_screensaver(Window win, bool enable);
+void x11_suspend_screensaver_xdg_screensaver(Window win, bool enable);
```
Comment (nguillaumin) [inline gfx/common/x11_common.h]: > Should be static. If you want the dispatcher function above the implementations, prototypes work fine.

Happy to do so, although I don't really understand why since my C is rusty, and no other functions on this file are stataic.

File: gfx/common/x11_common.c [hunk 4]
```diff
@@ -147,6 +153,75 @@ void x11_set_window_attr(Display *dpy, Window win)
 
 void x11_suspend_screensaver(Window wnd, bool enable)
 {
+    x11_suspend_screensaver_xdg_screensaver(wnd, enable);
```
Comment (nguillaumin) [inline gfx/common/x11_common.c]: > You sure we want to call both of those? ...maybe we do.

I thought it wouldn't hurt, in case one of these failed...

File: gfx/common/x11_common.c (hunk 1 above)
Comment (Alcaro) [inline gfx/common/x11_common.c]: Not here. x11_window_destroy doesn't check if dbus_screensaver_cookie is nonzero.

File: gfx/common/x11_common.h (hunk 3 above)
Comment (Alcaro) [inline gfx/common/x11_common.h]: One has to be the first.

They're not used outside that file, and shouldn't be. They're just implementation details. Not really important, just a cleanup.

File: gfx/common/x11_common.c (hunk 4 above)
Comment (Alcaro) [inline gfx/common/x11_common.c]: Yeah, doesn't hurt. Doubt it helps either, but no harm done.

File: gfx/common/x11_common.c (hunk 2 above)
Comment (Alcaro) [inline gfx/common/x11_common.c]: Then that too is buggy. No point fixing it in this PR, but let's not clone the same mistake elsewhere. You've got an uninhibit function in x11_window_destroy, just move it here. Minus the dbus disconnect stuff, there's no need for that at all; the kernel will disconnect you when the process exits.

**Comment by nguillaumin** [comment]
I pushed a new commit that should address the code review comments, feedback welcome. I kept the part that closes the dbus connection as that's the only way to clean up with `dbus_connection_unref()`.

To answer previous questions
* Yes it's an optional compile time dependency
* And I think suspending screensaver via DBus should be attempted by default, not be a configure option because I feel it's something that should just "work" without further config. If we make it an option, the the `xdg-screensaver` method should also be an option, I don't see why one should have special treatment? Note that if that the DBus connection cannot be established nothing bad will ensure, and if it can be established but nothing listens on the bus to the specific inhibition message then nothing will happen.

Thanks!

**Comment by twinaphex** [comment]
OK, how many objections still remain and can we start fast-tracking this through?

**Comment by orbea** [comment]
I compiled retroarch and now I have this, its not cool at all.
`libdbus-1.so.3 => /usr/lib64/libdbus-1.so.3 (0x00007f2c1de1c000)`
