### PR TITLE
(Ozone) Add savestate thumbnails

### LINKED ISSUE #10620: Save State screenshot thumbnails do not work with 'Ozone' menu driver
## Description
For a long time now, if configured in settings/saving/save state thumbnails, when you would select a save state slot in the quick menu, you would get a thumbnail of a screenshot, which is very useful if you're trying to avoid saving over a particular state saved previously.

### Expected behavior
You select a state slot in the 'quick menu,' and a thumbnail appears, indicating which save state you are getting ready to load or save over top of.

### Actual behavior

No thumbnail appears.

### Version/Commit
RetroArch 1.86, current stable

### Environment information

- OS: Windows 10

Please do not suggest that I simply switch back to the 'XMB' menu driver, obviously I am aware that I can do that. Ozone is the new default, it is what is going to be used by everyone moving forward, and I am simply trying to get the same functionality I had before, on an otherwise very nice interface.

### LINKED ISSUE #13863: Save state images are not viewable from within RetroArch
### Expected behavior

Screenshots created alongside save states should be viewable from within RetroArch in order to make save state slot selection easier.

### Actual behavior

Generating screenshots for save states creates images that get placed into the savestates folder, but inside RetroArch they serve no purpose.

### Version/Commit
1.10.3

### PR DESCRIPTION
**Pull request by sonninnos**
## Description

Mostly copypasted from XMB, and thus should be operating in similar fashion, with or without savestate submenu.

## Related Pull Requests

Closes #13863
Closes #10620

## Reviewers

@jdgleaver

### CODE REVIEW

File: menu/drivers/ozone.c [hunk 1]
```diff
@@ -562,6 +564,13 @@ struct ozone_handle
    char tab_path[PATH_MAX_LENGTH];
    char fullscreen_thumbnail_label[255];
 
+   /* These have to be huge, because runloop_st->name.savestate
+    * has a hard-coded size of 8192...
+    * (the extra space here is required to silence compiler
+    * warnings...) */
+   char savestate_thumbnail_file_path[8204];
```
Comment (LibretroAdmin) [inline menu/drivers/ozone.c:571]: I wonder if we can eventually vastly reduce the size of runloop_st->name.savestate. Perhaps it's best if we work with base paths and only put together the 'full path' right before a file I/O call.

Comment (sonninnos) [reply menu/drivers/ozone.c:571]: Yep, that current way does not seem optimal, but since it is like that in XMB, I didn't give it too much thought for now.

**Comment by sonninnos** [comment]
Okeydokey, should be covered now.
