### PR TITLE
(Discussion) about video driver shader compatibility (+ proper fix for #8834)

### LINKED ISSUE #8834: Shaders not loaded properly when RetroArch is started trough command-line (glcore)
## Description

When a game is loaded via the command-line, shaders won't be loaded, despite showing up as active in the shader menu. Only after pressing 'Apply Changes' will they be loaded.

This seems to only happen with the glcore video driver.

### Steps to reproduce the bug

1. Set video driver to glcore
2. Load a slang shader / Set a shader preset
3. Exit RetroArch
4. Run `retroarch.exe -L .\cores\snes9x_libretro.dll "Your Favorite Game.sfc"` or `retroarch.exe -L .\cores\mednafen_psx_hw_libretro.dll "Your Other Favorite Game.cue"`
5. Observe no shaders
6. Run RetroArch normally
7. Load Game
8. Observe shaders

### Bisect Results

It looks like this only happens with the glcore video driver. When using gl with GLSL shaders or vulkan with Slang shaders, the shaders are loaded properly. I haven't tested D3D or cg shaders, but at least the shader language doesn't seem to be the issue.

### What the logs shows

tl;dr exactly what you get from the description

The only difference in the logs is that, when started normally, this
```
[INFO] [GLCore]: Loading stock shader.
[INFO] [slang]: Building pass #0 (N/A)
(...)
```
appears when in the menu and `[INFO] [slang]: Compiling shader (...)` appears immediately after the game is loaded.
When started via the command-line, only the first message appears. It is not until 'Apply Changes' is pressed that the second message appears.

### Version/Commit

- RetroArch: 1.7.7 / 8092f601a6

### Environment information

- Windows 7 x64
- Compiler: GCC 7.3.0

### PR DESCRIPTION
**Pull request by LazyBumHorse**
## Description
This first commit changes the following:
 - `video_shader_parse_type()`'s fallback only worked for `NULL` paths and was wrongly used, it now returns RARCH_SHADER_NONE like video_shader_get_type_from_ext().
 - `video_shader_get_type_from_ext()` (and `video_shader_parse_type()`) should not be checking video driver flags, this is instead done by `video_shader_is_supported()`
 - `video_driver_get_all_flags()` did not actually 'get' flags, changed to `video_driver_test_all_flags()`

These changes makes it possible to use `video_shader_parse_type()` in a video driver's `init()` function without having to worry about the `poke_interface` not being set up yet.

## Related Issues

Properly fixes #8834.

Prior to #8894 and #8895, `video_shader_parse_type()` would not return the correct type of the shader, because of an internally failing `video_driver_test_flags()` call.
The 2 commits just hid the problem by setting the flags in the context driver instead.

Since those internal get_flags() calls are now removed, the actual shader type is returned and gl_core.c itself checks if the type is supported in `gl_core_init_filter_chain()`.

The exact same applies to vulkan.c in `vulkan_init_filter_chain()`, although it was never an issue there, because the context drivers set the `GFX_CTX_FLAGS_SHADERS_SLANG` flag.

## Possible bugs

d3d.c and metal.c might require additional context driver flag checks and I can test neither.

I think I also hit another separate bug in gl.c's `gl2_shader_init()`:

If I hardcode `type` to `RARCH_SHADER_SLANG` then I get the message
> [GL]: Not loading any shader, or couldn't find valid shader backend. Continuing without shaders.\n

followed by a black screen.

`type` usually can't be Slang because of a "fail-safe":  `check_shader_compatibility()` in configuration.c.
So if "video_shader" is set to a Slang shader in your config, it will be blanked out because of the checks in `check_shader_compatibility()`.
The `retroarch_get_shader_preset()` call in `gl2_shader_init()` is therefore empty and `type` is set to a default.

I'm hesistant to add the missing context driver flag checks because the alternative is a black screen.

## Discussion

The whole shader compatibility situation is very messy.

There are video and context driver flags which currently are redundant and confusing, e.g. the video drivers gl_clore.c and vulkan.c set the `GFX_CTX_FLAGS_SHADERS_SLANG` flag, which - to me - says "I support Slang no matter the context", but then the same flag gets set in the context drivers, which - to me - says "Slang support depends on the context".
gl.c is an example of a video driver which sets no shader flags, so the context drivers have to set them, which is fine.

Then there's `check_shader_compatibility()` which I'm critical of, because it uses simple hardcoded rules which may or may not agree with the video/context driver flags.
Letting it `return true;` led me to the black screen in gl, which seems to be an initialization problem which was covered up.

IMHO it is the responsibility of the video driver to deal with any shader we throw at it (and it can always ask the context for help too) and gl doesn't seem to deal well with Slang.

### CODE REVIEW

**Comment by orbea** [comment]
@LazyBumHorse We haven't had a knowledgeable and regular developer for the graphics code for a while, its honestly a mess in desperate need of help. :)

**Comment by LazyBumHorse** [comment]
I guess I'll look into preventing that black screen next then.

I'm not sure, but does gl.c not work without shaders at all?
It would make sense being called gl2 then, since OpenGL 2.0 introduced GLSL, I guess that's the main distinction to gl1.

If that is true, that means that the fix is to further improve the shader type check.
I'm also not sure why it continues without shaders when this'll lead to nothing but a black screen.

**Comment by fr500** [comment]
@LazyBumHorse I wrote check shader compatibility and I did it because there was no better way before.
RA used to be a crashfest whenever a "wrong shader" was loaded.

twinaphex tried the shader flags thing back then and it bombed badly.

Of course like you mentioned it needs manual maintenance and is not 100% reliable, but I do think a simple helper option that can tell if the shaders are compatible is the way to go for core/game presets.

Avoiding a shader load when it's flat out incompatible is better than it just erroring out.

**Comment by LazyBumHorse** [comment]
@fr500
> twinaphex tried the shader flags thing back then and it bombed badly.

>  I do think a simple helper function that can tell if the shaders are compatible is the way to go for core/game presets, for switching on the fly, for filtering shaders on the file picker, etc.

I'm confused, RA currently _does use_ the shader flags to filter shaders in the file picker and that seems to work fine, doesn't it?
If it doesn't, it should always be possible to adjust the flags of the, let's say, context driver accordingly.
That way we can have just 1 type of shader check, which is fully determined by the video/context driver.

`check_shader_compatibility()` ultimately only applies to the shader initialization* and it only adds a simple Slang shader check.
I checked it, it only has an effect on d3d9-12, metal, gl_core, gx2_gfx, gl and vulkan's `init()`*.
Therefore it should be easy to incorporate those checks into the drivers themselves.
At least gl_core and vulkan already handle everything you throw at them.

*`check_shader_compatibility()` changes the value of the settings's `paths.path_shader`, which is effectively only used in `retroarch_get_shader_preset()`, which is only used in those video drivers (and in menu_shader.c which already uses shader flag checks).

>RA used to be a crashfest whenever a "wrong shader" was loaded

Is there a an issue number where I can read up on the crashes that happened?

The black screen in found in gl (which was fixed by `check_shader_compatibility()`) isn't really due to wrong shaders being fed in, but it's caused by the broken fallback logic in `video_shader_parse_type()` which would return `RARCH_SHADER_NONE` instead of GLSL or Cg, thus disabling the shader output.

I'm currently working on gl, so that all the shader checking happens in 1 place.

**Comment by fr500** [comment]
Yeah I figure it does now, but back then there wasn't any filtering in place.
I honestly and wholeheartedly think that function should be removed now that someone with the knowledge is taking a good look at it.

About the crashes, sadly no, it was just a known factor, load Cg in a driver that doesn't support it, crash, and so on.

What are you gonna do about drivers that support more than one backend. I built some prioritization capability in check_shader_compatibility IIRC, it would prefer GLSL to Cg in GL for instance (haven't checked the actual code to see if that's accurate).

The way per-core/per-game presets work is by looking into a folder and loading the shaders based on shader backend compatibility (which uses the extension) IIRC. For the few drivers that support more than one backend you have to have a priorization/preference method in place.

**Comment by orbea** [comment]
Concerning crashes issue https://github.com/libretro/RetroArch/issues/4804 is somewhat related.

**Comment by LazyBumHorse** [comment]
@fr500 

>  I built some prioritization capability in check_shader_compatibility IIRC, it would prefer GLSL to Cg in GL for instance

> The way per-core/per-game presets work is by looking into a folder and loading the shaders based on shader backend compatibility (which uses the extension) IIRC.

That was actually (the answer to) a question I was having, but I don't think I've yet seen the code.
Can you give me a hint of where to find it?

There's a very similar kind of priorization already going on inside gl.c, e.g. it tries to fallback to a default when it can't load a shader (though that part is a bit broken in master) and then there is a fallback mechanism in `gl_shader_driver_set_backend()` which uses GLSL if it can't use Cg.
https://github.com/libretro/RetroArch/blob/1120a7e490888abf5e41a7a71425eb06c916b186/gfx/drivers/gl.c#L2014-L2019
I've already refactored both into a `gl2_get_fallback_shader_type()` function, which takes a shader type (can be none) and returns that type if it is supported, or a supported fallback/default, so it can already prioritize.

There are also these `#define`s whiche have at least a bit of priorization in them (it's used in gl.c):
https://github.com/libretro/RetroArch/blob/1120a7e490888abf5e41a7a71425eb06c916b186/gfx/video_driver.h#L60-L68

---

@orbea Thanks for the link!
I remember reading that thing, thinking "I don't want to touch that with a ten foot pole." ^^

File: gfx/video_shader_parse.c [hunk 1]
```diff
@@ -1178,32 +1174,23 @@ enum rarch_shader_type video_shader_get_type_from_ext(const char *ext,
...
          )
-      {
-         if (video_driver_get_all_flags(&flags, GFX_CTX_FLAGS_SHADERS_CG))
-            return RARCH_SHADER_CG;
-      }
+         return RARCH_SHADER_CG;
    }
 
    {
       gfx_ctx_flags_t flags;
```
Comment (KostasAndrianos) [inline gfx/video_shader_parse.c]: Isn't this redundant?

File: gfx/video_shader_parse.c [hunk 2]
```diff
@@ -1178,32 +1174,23 @@ enum rarch_shader_type video_shader_get_type_from_ext(const char *ext,
...
          )
-      {
-         if (video_driver_get_all_flags(&flags, GFX_CTX_FLAGS_SHADERS_GLSL))
-            return RARCH_SHADER_GLSL;
-      }
+         return RARCH_SHADER_GLSL;
    }
 
    {
       gfx_ctx_flags_t flags;
```
Comment (KostasAndrianos) [inline gfx/video_shader_parse.c]: This too

File: gfx/video_shader_parse.c (hunk 1 above)
Comment (KostasAndrianos) [inline gfx/video_shader_parse.c]: This is unused

File: gfx/video_shader_parse.c (hunk 2 above)
Comment (KostasAndrianos) [inline gfx/video_shader_parse.c]: This is unused, too.

File: gfx/video_shader_parse.c (hunk 1 above)
Comment (KostasAndrianos) [inline gfx/video_shader_parse.c]: This is unused

File: gfx/video_shader_parse.c (hunk 2 above)
Comment (KostasAndrianos) [inline gfx/video_shader_parse.c]: This too.

**Comment by LazyBumHorse** [comment]
@KostasAndrianos Thanks for reviewing! Fixed for next commit, whenever that's done.

**Comment by LazyBumHorse** [comment]
I guess I can push what I have so far, what's the harm? Still WIP.

**Comment by orbea** [comment]
Should PRs #8894 and #8895 be reverted with this change?

**Comment by LazyBumHorse** [comment]
They _can_ be reverted in this branch, but I'm not yet set on that.

It definitely doesn't hurt if the flags are set in the context drivers and there might even be an argument in which to say that shader flags should _only_ be set in the context driver, because that way you can poll them from everywhere, even from the `init()` of the video driver, which might make things easier.

The current plan is to get the questions about gl.c answered (see TODO messages in the last commit), then move on to check d3d9-11, metal, and gx2_gfx.
By then I'll probably know what to do about those 2 commits.

**Comment by LazyBumHorse** [comment]
## Description
Alright, 2nd commit and the final goal isn't that far off.
This should adress the shader type checks in d3d9-12, gl_core, gx2_gfx, gl and vulkan.
There's a plethora of other small stuff:
 - gl.c: refactor backend fallback into more general `gl2_get_fallback_shader_type`
 - d3d9-12, gl_core, gx2_gfx, gl, vulkan: more consistent shader init and `set_shader`, if `string_is_empty(path)` stock will be used
 - configuration.c: remove `check_shader_compatibility()`
 - shader_glsl.c, shader_gl_cg.c: use `video_shader_get_type_from_ext`
 - shader_gl_cg.c: add shader type check with fallback to stock like in shader_glsl.c
 - menu_shader.c: use `enum rarch_shader_type` instead of `unsigned`
 - video_shader_parse.c: add `video_shader_to_str` for easier logging
 - remove `type` from `struct video_shader`, which was always set to CG and wrongly used in lang_process.cpp's `slang_process()` (has no further consequences because the code is unused)
 - command.c: removed `#ifdef HAVE_MENU` from `CMD_EVENT_SHADERS_APPLY_CHANGES` because the called function has an internal `#ifdef HAVE_MENU`, this may fix a bug

## Issues & Comments:

 - Metal doesn't fall back to stock at all (in master as well), `setShaderFromPath()` (in metal_common.m) needs to be changed, but I can neither compile nor test it.

 - d3d9 would keep the shader if it couldn't load the new one, which is actually nice behavior, but inconsistent with the other video drivers and the menu would turn off shaders on failure anyways, so this was sadly removed.

 - If gl doesn't find a supported shader backend, it'll continue without one, resulting in a black screen. (Unchanged from before)

 - removing `check_shader_compatibility()` has a negative impact the on preset selection, if a .cgp exists, it'll be used in any video driver, which is the main reason I don't want this to be merged yet.

## TODO:
 - metal_common.m `setShaderFromPath` should set stock shader if `string_is_empty(path)`
 - move all shader flags into context drivers
 - refactor shader preset selection and compatibility checks:
   - move and refactor preset selection from configuration.c to retroarch.c's `retroarch_get_shader_preset()`
   - finally add proper shader compatibility check

File: command.c [hunk 3]
```diff
@@ -2513,9 +2513,7 @@ TODO: Add a setting for these tweaks */
          ui_companion_event_command(cmd);
          break;
       case CMD_EVENT_SHADERS_APPLY_CHANGES:
-#ifdef HAVE_MENU
```
Comment (twinaphex) [inline command.c]: Why did you get rid of this HAVE_MENU ifdef? We should allow for the possibility of being able to compile without the menu.

File: gfx/drivers/d3d10.c [hunk 4]
```diff
@@ -951,13 +949,9 @@ d3d10_gfx_init(const video_info_t* video,
...
    font_driver_init_osd(d3d10, false, video->is_threaded, FONT_DRIVER_RENDER_D3D10_API);
 
-   if (settings->bools.video_shader_enable)
-   {
-      const char* ext = path_get_extension(retroarch_get_shader_preset());
-
-      if (ext && !strncmp(ext, "slang", 5))
-         d3d10_gfx_set_shader(d3d10, RARCH_SHADER_SLANG, retroarch_get_shader_preset());
-   }
+   const char *shader_preset   = retroarch_get_shader_preset();
```
Comment (twinaphex) [inline gfx/drivers/d3d10.c]: C89 compliance issue. Variables need to be declared either at the top of a code block or function.

File: gfx/drivers/d3d11.c [hunk 5]
```diff
@@ -1025,13 +1025,9 @@ d3d11_gfx_init(const video_info_t* video, const input_driver_t** input, void** i
...
    font_driver_init_osd(d3d11, false, video->is_threaded, FONT_DRIVER_RENDER_D3D11_API);
 
-   if (settings->bools.video_shader_enable)
-   {
-      const char* ext = path_get_extension(retroarch_get_shader_preset());
-
-      if (ext && !strncmp(ext, "slang", 5))
-         d3d11_gfx_set_shader(d3d11, RARCH_SHADER_SLANG, retroarch_get_shader_preset());
-   }
+   const char *shader_preset   = retroarch_get_shader_preset();
```
Comment (twinaphex) [inline gfx/drivers/d3d11.c]: Same C89 issue here. Variables need to be declared either at the top of a code block or function.

File: gfx/drivers/d3d12.c [hunk 6]
```diff
@@ -999,13 +997,9 @@ d3d12_gfx_init(const video_info_t* video, const input_driver_t** input, void** i
...
    font_driver_init_osd(d3d12, false, video->is_threaded, FONT_DRIVER_RENDER_D3D12_API);
 
-   if (settings->bools.video_shader_enable)
-   {
-      const char* ext = path_get_extension(retroarch_get_shader_preset());
-
-      if (ext && string_is_equal(ext, "slangp"))
-         d3d12_gfx_set_shader(d3d12, RARCH_SHADER_SLANG, retroarch_get_shader_preset());
-   }
+   const char *shader_preset   = retroarch_get_shader_preset();
```
Comment (twinaphex) [inline gfx/drivers/d3d12.c]: Same here. Variables need to be declared either at the top of a code block or function.

File: gfx/drivers/gl.c [hunk 7]
```diff
@@ -864,10 +862,8 @@ static GLenum gl2_min_filter_to_mag(GLenum type)
       case GL_NEAREST_MIPMAP_NEAREST:
          return GL_NEAREST;
       default:
-         break;
```
Comment (twinaphex) [inline gfx/drivers/gl.c]: I'd rather you change this back to what it was.

I'd rather have a clear return at the end of the function instead of leaving it empty like that.

File: gfx/drivers_shader/shader_gl_cg.c [hunk 8]
```diff
@@ -1074,16 +1074,27 @@ static void *gl_cg_init(void *data, const char *path)
...
-         && string_is_equal(path_get_extension(path), "cgp"))
    {
-      if (!gl_cg_load_preset(cg, path))
-         goto error;
-   }
-   else
-   {
-      if (!gl_cg_load_plain(cg, path))
-         goto error;
+      bool is_preset;
```
Comment (twinaphex) [inline gfx/drivers_shader/shader_gl_cg.c]: C89 compliance issue. Variables need to be declared either at the top of a code block or function.

File: gfx/video_shader_parse.c [hunk 9]
```diff
@@ -65,10 +65,8 @@ static const char *wrap_mode_to_str(enum gfx_wrap_type type)
       case RARCH_WRAP_MIRRORED_REPEAT:
          return "mirrored_repeat";
       default:
-         break;
+         return "???";
```
Comment (twinaphex) [inline gfx/video_shader_parse.c]: Rather you change this back to what it was. I want the function to always return something at the end of the function.

File: gfx/video_shader_parse.c [hunk 10]
```diff
@@ -1121,6 +1118,27 @@ void video_shader_write_conf_cgp(config_file_t *conf,
...
+         return "GLSL";
+      case RARCH_SHADER_SLANG:
+         return "Slang";
+      case RARCH_SHADER_METAL:
+         return "Metal";
+      case RARCH_SHADER_NONE:
+         return "none";
+      default:
+         return "???";
+   }
```
Comment (twinaphex) [inline gfx/video_shader_parse.c]: Same here. A function returning a const char * should always return something, so just change this back to something where "default" would do a break; first, then return "???" at the end.

File: menu/menu_shader.c [hunk 11]
```diff
@@ -206,9 +206,9 @@ static const char *shader_get_preset_extension(unsigned type)
       case RARCH_SHADER_HLSL:
       case RARCH_SHADER_CG:
          return file_path_str(FILE_PATH_CGP_EXTENSION);
+      default:
+         return NULL;
    }
```
Comment (twinaphex) [inline menu/menu_shader.c]: Same here. Do a default: break instead, then return NULL at the end of the function.

File: command.c (hunk 3 above)
Comment (LazyBumHorse) [reply command.c]: The function has an internal HAVE_MENU ifdef, so I thought this was some kind of bug.
I undid this locally however because I don't understand it well enough, so this won't be in the finished pull request.

**Comment by LazyBumHorse** [comment]
@twinaphex Thanks for all the hints, will resolve soon!
(I thought Travis CI would give me errors for messing up the C89 declaration style, though...)

The TODO is for this pull request because they are necessary to not have any regressions.
I'm actually almost finished too!

There's only one last problem:
In master, the video drivers `d3d10`, `d3d11`, `d3d12`, `metal`, `glcore`, `vulkan` and `gx2` do set the Slang shader flag, meaning Slang was set as supported for every context driver.
Since the plan is to put all the shader flags solely in the context drivers, it'd probably be overkill to literally put a long condition á la `if (string_is_equal(video_driver_get_ident(), "d3d10") || ...) ....` into every single one of them.

So what I need help with is deciding which of these context drivers need Slang flags:
`cgl_ctx`, `cocoa_gl_ctx`, `gdi_ctx`, `mali_fbdev_ctx`, `opendingux_fbdev_ctx`, `orbis_ctx`, `osmesa_ctx`, `ps3`, `qnx_ctx`, `sdl_gl_ctx`, `switch`, `vc_egl_ctx`, `vivante_fbdev_ctx`, `xegl_ctx`

Or rather I'd like to know which of these definitely _do not_ require them.
In the end it's better to put them in if unsure, because otherwise we just eliminated shaders for supported platform.

I'm also unsure for which video drivers I should not only put a HAVE_SLANG but also a HAVE_SPIRV_CROSS ifdef.
In master only d3d10-12 have both, but it seems like metal, glcore and vulkan need them too?
Not sure about gx2.

**Comment by twinaphex** [comment]
> I'm also unsure for which video drivers I should not only put a HAVE_SLANG but also a HAVE_SPIRV_CROSS ifdef.

Yes, assume for now that both HAVE_SLANG and HAVE_SPIRV_CROSS need to be both defined for slang support to even be available in RetroArch.

> So what I need help with is deciding which of these context drivers need Slang flags:
cgl_ctx, cocoa_gl_ctx, gdi_ctx, mali_fbdev_ctx, opendingux_fbdev_ctx, orbis_ctx, osmesa_ctx, ps3, qnx_ctx, sdl_gl_ctx, switch, vc_egl_ctx, vivante_fbdev_ctx, xegl_ctx

OK,

one thing you should keep in mind is that slang shader support (so the slang extension) should only show up inside the shader preset/pass filebrowser IF the video driver / context driver actually supports it.

cgl_ctx - I guess it will depend on whether the GL version here targets GL 3.0+ or later, so when the "glcore" video driver is used. For now this is not the case, in the future it could be.
cocoa_gl_ctx - if "glcore" video driver is used, then slang support should be queried.
gdi_ctx - will never support slang.
mali_fbdev_ctx - will probably never support slang.
opendingux_fbdev_ctx - will probably never support slang.
orbis_ctx - only if "glcore" video driver is used.
osmesa_ctx - will probably never support slang. Not sure about this one though.
ps3 - will never support slang.
qnx_ctx - will never support slang. Is stuck on GLES2.
sdl_gl_ctx - will probably never support slang.
switch - only if "glcore" video driver is used.
vc_egl_ctx - will probably never support slang. Is stuck on GLES2 for now.
vivante_fbdev_ctx - will probably never support slang.
xegl_ctx - only if "glcore" video driver is used.

While I don't know yet if fbdev excludes the use of GLES3/GL3.0, for now I err on the side of caution and assume it won't.

**Comment by LazyBumHorse** [comment]
## Description

Alright, final commit is done, proper shader compatibility checks!

 - move shader flags from the video drivers to the context drivers
 - rework config_load_shader_preset() from configuration.c into retroarch_load_shader_preset() in retroarch.c with proper compatibility check
 - implicitly call retroarch_load_shader_preset() in retroarch_get_shader_preset() once per core/content life cycle
 - use video_shader_is_supported() instead of video_driver_test_all_flags() where appropriate
 - remove GFX_CTX_FLAGS_NONE because it is meaningless


I should explain how this works.
So before, `config_load_shader_preset()` would be called just before `core_init()`, which implies that neither the video nor context driver were set up yet, therefore it could not poll shader flags and only do a rough compatibility check.
Now, there's `retroarch_load_shader_preset()` which polls context driver shader flags and is implicitly called by `retroarch_get_shader_preset()`, which is what the video drivers use to find out what shader they should load in their `init()`.
The assumption is that the context driver is set up in a video drivers `init()` before shaders are loaded, which _should_ be true for all video drivers (it is for d3d9-12, gl, glcore, vulkan, gx2 and metal).

`retroarch_load_shader_preset()` also has an (arbitrary) internal priorization, which goes like this:
GLSL > Slang > Cg > HLSL
This only matters for multi-shader video drivers like gl and it could still be worked on because it's not consistent with how gl internally prioritizes its backend, but I think as long als GLSL comes before Cg, everyone should be happy.

I did not try to implement fallback to stock in metal's `setShaderFromPath`, because that would be guesswork, I'll probably just open an issue for that.

---

I should also mention that all this needs review and testing, it's in a 'it works on my machine'™ state.

**Comment by LazyBumHorse** [comment]
Oops, I should rebase...

**Comment by twinaphex** [comment]
Yeah, my sincere apologies for that. It's best to rebase after this.

**Comment by LazyBumHorse** [comment]
Huh, I thought my git was glitching out, seeing the 4000 line changes of video_driver.c/h.

@twinaphex Why merge all the driver interfaces into retroarch.c? I found the separation quite nice.

**Comment by twinaphex** [comment]
It's going back to the old design of SSNES where we didn't have all these 'driver' source files. Once all the driver parts are in one source file, I should be able to nicely refactor a bunch of things which should result in faster code + we should be able to significantly cut down on file size of that single source file.

**Comment by LazyBumHorse** [comment]
File size was the main concern, cutting sounds good though, thanks for the quick answer.
I'll rebase soon enough.

**Comment by twinaphex** [comment]
Apart from that, nothing was really changed. Sorry for the inconvenience and that this happened at the same time, it was not intentional at least for it to be right on the cusp of you finishing this PR. On the upside, it should not be that hard to rebase the changes since the code more or less stayed the same, just moved around.

**Comment by LazyBumHorse** [comment]
Yeah, no worries, should be easy peasy, those ~16 changed lines I can do manually.

**Comment by LazyBumHorse** [comment]
Should be good now.

**Comment by twinaphex** [comment]
@LazyBumHorse There is a problem with this PR.

With d3d10/11/12, 'Shaders' no longer show up in the Quick Menu.

**Comment by twinaphex** [comment]
This fixes 'Shaders' no longer showing for D3D10/11/12.

https://github.com/libretro/RetroArch/commit/5d91af629e9837667cfb424902e6796b222d5867

However, this issue still remains -

```
if you select "glcore" as the video driver, it should only show slang shaders inside the file browser instead of glsl and slang at the same time. Before this was working properly.
```

**Comment by LazyBumHorse** [comment]
Which context drivers is this happening with? Putting the flags in the video driver will cause init issues again.

**Comment by LazyBumHorse** [comment]
Wait, does d3d10-12 not use any?

**Comment by LazyBumHorse** [comment]
Can't reproduce the glcore issue.
Every `if (string_is_equal(video_driver_get_ident(), "glcore")) ... slang` is followed by an `else ... glsl`, so there should be no change to before.
Emphasis on "change", it could be that GLSL is/was set without a check in some driver.

**Comment by twinaphex** [comment]
D3D10-11-12 has no context drivers, correct.

Context drivers are usually a thing for OpenG and Vulkan drivers.

**Comment by LazyBumHorse** [comment]
Wish somebody told be before :cry: 
Announced moving the flags with big letters... oh well.

**Comment by twinaphex** [comment]
Anyway, no hard feelings here, and I'm affording you the time to look into it. I won't revert anything or so so that you have some time to research this at your own pace without feeling stressed.

BTW, you can always visit us on Discord, we'd love to have you. You can find the link on retroarch.com. Just look for Autechre on there, that's me.

**Comment by LazyBumHorse** [comment]
Alright, about glcore, there's these context drivers which might require tweaking:
`android_ctx`, `cocoa_gl` in the ES case, `emscriptenegl_ctx`, `mali_fbdev_ctx`, `opendingux_fbdev_ctx`, `osmesa_ctx`, `qnx_ctx`, `vc_egl_ctx`, `vivante_fbdev_ctx`
Which of these support glcore?
I could add a case for all of them just to be sure.

I'll look into discord next, might need a new eMail, though...

**Comment by twinaphex** [comment]
android_ctx - it can support glcore later on.
cocoa_gl      - it can support glcore, probably for both GL and GLES.
qnx_ctx - GLES2 only. so no glcore.
vivante_fbdev_ctx - don't think glcore will support this
emscriptenegl_ctx - GLES2 only. no glcore.
mali_fbdev_ctx - don't think glcore will support this.
opendingux_fbdev_ct x- don't think glcore will support this.
osmesa_ctx - don't think glcore will support this.
vc_egl_ctx - GLES2 only. so no glcore

I'm not sure about fbdev, I will ask maister later. For now just assume glcore won't work there. If there is any update on this later on, I will inform you about it.
